### ISSUE TITLE
Add path_prefix parameter to cloud delivery option

### ISSUE THREAD

**Issue by guyon-planet** [planetlabs/planet-client-python#1017]
I would like a parameter in the [delivery options ](https://github.com/planetlabs/planet-client-python/blob/4873a4856ef3247ba6e5e5fd7949e90bddad7e11/planet/subscription_request.py#L371)that allows me to add a prefix.

I know the API allows it: [https://developers.planet.com/docs/subscriptions/delivery/...](https://developers.planet.com/docs/subscriptions/delivery/#:~:text=%22delivery%22%3A%20%7B%0A%20%20%20%20%22type%22%3A%20%22google_cloud_storage%22%2C%0A%20%20%20%20%22parameters%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22bucket%22%3A%20%22your%2Dgcs%2Dbucket%22%2C%0A%20%20%20%20%20%20%20%20%22credentials%22%3A%20%22c29tZWNyZWRzZm9yeW91cmdjc2J1Y2...%22%2C%0A%20%20%20%20%20%20%20%20%22path_prefix%22%3A%22optionalsubfolder1/optionalsubfolder2%22%0A%20%20%20%20%7D%0A%7D)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pl-gideon** [comment]
@guyon-planet I plan to get around to this ... _soon_ - it is low effort and valuable, thanks for creating an issue for it.
