### ISSUE TITLE
Dunder version number / PEP 396 

### ISSUE THREAD

**Issue by kscottz** [planetlabs/planet-client-python#102]
I was putting together a requirements file that included the Planet python client. There is no dunder version method available as specified in [PEP 396](https://www.python.org/dev/peps/pep-0396/).

**Comment by ischneider** [comment]
From what I understand, does this suffice for `dunder version` (I'm was not aware of this term)?:

https://github.com/planetlabs/planet-client-python/blob/master/planet/api/__init__.py#L22

e.g. `from planet import api; print api.__version__`

As for _why_ this has been implemented as a namespace package (at the `planet.api` level vs `planet`), see https://github.com/planetlabs/planet-client-python/pull/35

For requirements, AFAIK, requirements resolution only deals w/ the `setup.py` version (which is read from `planet/api/__init__.py`)
https://github.com/planetlabs/planet-client-python/blob/master/setup.py#L56

**Comment by sarasafavi** [comment]
I happened to be looking at PEP-396 yesterday before I noticed this issue existed! 

My read: with #35 in mind, once https://github.com/planetlabs/planet-client-python/pull/123 is in we should be back in compliance (with our `__version__` existing on a module within an unversioned namespace package).
