### ISSUE TITLE
Example in docs for running search against Data API doesn't work

### ISSUE THREAD

**Issue by favyen2** [planetlabs/planet-client-python#1054]
**Expected behavior**
The example at https://planet-sdk-for-python-v2.readthedocs.io/en/stable/get-started/upgrading/#asynchronous-methods run successfully when API key is provided, producing a list of items from the API.

**Actual behavior (describe the problem)**
It runs into an error because `client.search` is closed outside of the with block. Here is the code snippet:

```python
import asyncio
from datetime import datetime
from planet import Session
from planet import data_filter as filters

async def do_search():
    async with Session() as session:
        client = session.client('data')
        date_filter = filters.date_range_filter('acquired', gte=datetime.fromisoformat("2022-11-18"), lte=datetime.fromisoformat("2022-11-21"))
        cloud_filter = filters.range_filter('cloud_cover', lte=0.1)
        download_filter = filters.permission_filter()
    return [item async for item in client.search(["PSScene"], filters.and_filter([date_filter, cloud_filter, download_filter]))]

items = asyncio.run(do_search())
```

Here is the error:

```
RuntimeError: Cannot send a request, as the client has been closed.
```

**Related Issues**
none

**Workaround**
The example should be corrected:

```python
import asyncio
from datetime import datetime
from planet import Session
from planet import data_filter as filters

async def do_search():
    async with Session() as session:
        client = session.client('data')
        date_filter = filters.date_range_filter('acquired', gte=datetime.fromisoformat("2022-11-18"), lte=datetime.fromisoformat("2022-11-21"))
        cloud_filter = filters.range_filter('cloud_cover', lte=0.1)
        download_filter = filters.permission_filter()
        return [item async for item in client.search(["PSScene"], filters.and_filter([date_filter, cloud_filter, download_filter]))]

items = asyncio.run(do_search())
```

**Minimum, Complete, Viable Code Sample**
It is an example from the docs so it is already minimal.

**Environment Information**
* Operation System Information (`python -c "import platform; print(platform.platform())"`)

Linux

* Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)

3.12.2

* Planet package version (`planet -v`)
```
$ planet -v
Usage: planet [OPTIONS] COMMAND [ARGS]...
Try 'planet --help' for help.

Error: No such option: -v
```

**Installation Method**

pip

**Comment by stephenhillier** [comment]
Thanks @favyen2! 

I opened #1055 to fix these two issues. I also note the issue template wants you to run `planet -v` which isn't a valid option- I'll follow up and see what we can do there (either fix the issue template or the option).

If you have any other issues or feedback, please don't hesitate to open up another issue or follow up here!
