### ISSUE TITLE
prompt for api key and offer to store/remember

### ISSUE THREAD

**Issue by ischneider** [planetlabs/planet-client-python#11]
from @cholmes 

> I first get 'Error: InvalidAPIKey: No API key provided'. Would be cool if it could prompt me for my key then - to just enter it manually and then do the request for me (probably being able to escape out if I don't have it). Would be cooler if providing it then set the key for me, at least for that session (and ideally for more than that session).

see also #6 (the key provided at the prompt could be stored in a dot-file)

**Comment by sgillies** [comment]
We're not going to do this for v1. I'm not sure it's a must-have for v2, either. This is not a feature one would ever want to have in a Python library. In a CLI, maybe, but it isn't a big burden for a user to store credentials in a file or in the environment.

**Comment by cholmes** [comment]
This request was for the CLI, and I do think philosophically we should be helping our CLI users by making things as smooth as possible - historically many have been new to the command line and though it's not a big burden to store credentials they wouldn't even know that's a thing. 

That said this request pre-dates the 'init' command, which more than solves the core usability for new users - a prompt for email and password and then storing the API key is even friendlier than what was suggested.
