### ISSUE TITLE
cli limits on activation?

### ISSUE THREAD

**Issue by robinkraft** [planetlabs/planet-client-python#116]
* When I'm using `--activate-only` for my AOI, `--dry-run` reports 235 items would be activated, while without `--dry-run` there are only 100 items being activated at a time.

```shell
$ planet data download --activate-only --geom lake.json --item-type PSScene4Band --asset-type visual --dry-run
would download approximately 235 assets from 235 items
$ planet data download --activate-only --geom lake.json --item-type PSScene4Band --asset-type visual
activating: 100          complete: 0              elapsed: 11              paging: False             pending: 0
```

This is the geojson in `lake.json`:

```json
{"type":"Polygon","coordinates":[[[-123.6239,47.9602],[-123.5748,47.9602],[-123.5748,48.0115],[-123.6239,48.0115],[-123.6239,47.9602]]]} 
```

**Comment by robinkraft** [comment]
Although the log updates to eventually show `paging: True`, activations stop after the initial 100.

**Comment by jreiberkyle** [comment]
When I attempt to recreate, while `activating` stays at 100, `elapsed` goes above 100.

e.g. 
```
planet data download \
    --geom lake.json --item-type PSScene4Band --asset-type visual \
    --activate-only --dry-run \
    --date acquired gt 2019-02-14
```
finds 247 items

```
planet data download \
    --geom lake.json --item-type PSScene4Band --asset-type visual \
    --activate-only \
    --date acquired gt 2019-02-14
```
goes all the way up to `elapsed` 182 before completing although `activating` stays at 100. I *think* the reason it only goes up to 182 is because the other 50 or so were already activated but I need to test.

The limit on concurrent activations to 100 is hardcoded in `downloader.py` and does not depend on page size or item count.

**Comment by sgillies** [comment]
My take on this is that the number in the `--dry-run` output can't be compared to the numbers in the progress bar/monitor widget. Also, the `--dry-run` option seems to be more or less the same thing as `planet data stats` and not a true dry run of activation or download. I'm going to mark this as a wontfix. We'll make the situation less confusing in the upcoming version.
