### ISSUE TITLE
--activate-only doesn't print URLs for downloading

### ISSUE THREAD

**Issue by robinkraft** [planetlabs/planet-client-python#117]
[The docs say](https://planetlabs.github.io/planet-client-python/cli/reference.html?highlight=activate%20only#cli-command-download) that using `--activate-only` `Outputs URLS for downloading.` I'm not seeing any URLs.

`planet data download --item-type PSScene3Band --asset-type visual --string-in id 20170902_182918_1031 --activate-only`

**Comment by robinkraft** [comment]
Actually, it turns out they print if you use the `--quiet` flag. That's not really what I expected :)

**Comment by sarasafavi** [comment]
closed with #124
