### ISSUE TITLE
--verbose flag doesn't seem to work

### ISSUE THREAD

**Issue by robinkraft** [planetlabs/planet-client-python#118]
I see the `--verbose` flag [in the docs](https://planetlabs.github.io/planet-client-python/cli/reference.html?highlight=verbose#general-options) and [in the code](https://github.com/planetlabs/planet-client-python/blob/8835672b4d08b8631696e7ecb033307b8862d13c/planet/scripts/cli.py#L49). But it doesn't seem to be active.

```shell
$ planet data download --item-type PSScene3Band --asset-type visual --string-in id 20170902_182918_1031 --verbose
Error: no such option: --verbose
```

**Comment by bosth** [comment]
Should work if you put it between the `planet` and the `data`.

**Comment by robinkraft** [comment]
Not the most obvious place to include it, but you're right it does work.

**Comment by bosth** [comment]
I think the intention was that verbosity (and a few other options, like authentication) are "top-level" and should be modifiers to `planet` rather than the subcommand.

**Comment by jreiberkyle** [comment]
May want to include documentation on how to specify verbosity (options are: `-v` for info logging and `-vv` for debug logging)

**Comment by sgillies** [comment]
The docs are not wrong, so I'm going to mark this a wontfix. In v2 we'll see what we can do to allow `-v` in subcommands as well.
