### ISSUE TITLE
win32api module issue on windows machine

### ISSUE THREAD

**Issue by samapriya** [planetlabs/planet-client-python#145]
I had this crop up on someone's windows computer when they installed the planet client
ImportError: **No module named 'win32api'**

Recommended fix is **pip install pywin32**

Would it great to check os type
something like
```python 
import os
import subprocess
if os.name=="nt":
    subprocess.call('pip install pywin32',shell=True)
```

Either in setup or during first run

**Comment by rmuellerjr** [comment]
I ran into this too. Up vote for taking care of this.
