### ISSUE TITLE
Post-maintenance 404 error from client.py

### ISSUE THREAD

**Issue by ldemaz** [planetlabs/planet-client-python#146]
Hello, we have developed a process for downloading scenes. This was working well up until late yesterday/today, but now is getting a 404 Error from [line 263](https://github.com/planetlabs/planet-client-python/blob/16354d7567db154ba840f868f3a1e8b9373d5468/planet/api/client.py#L263)

This is the error we are getting, which seems to relate to a failure to convert html to json:

```
https://api.planet.com/data/v1/item-types/PSScene4Band/items/20180217_074550_1024/assets
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That's an error.</ins>
  <p>The requested URL <code>/data/v1/item-types/PSScene4Band/items/20180217_074550_1024/assets/</code> was not found on this server.  <ins>That's all we know.</ins>
``` 

Any pointers on how to resolve this much appreciated.

**Comment by bosth** [comment]
Hi Lyndon, could you show the code (or command line parameters) that you are using to initiate the download?

**Comment by pomadchin** [comment]
Hi @bosth, so the code is very straightforward: 

```python
# in the example above item_type = PSScene4Band; scene_id = 20180217_074550_1024
item_url = 'https://api.planet.com/data/v1/item-types/{}/items/{}/assets'.format(item_type, scene_id)
result = requests.get(item_url, auth = HTTPBasicAuth(self.api_key, ''))
```

**Comment by bosth** [comment]
Hi @pomadchin , note that this code does not use the Planet Python client. It's just making calls t our API directly using Python.

**Comment by bosth** [comment]
@pomadchin That being said, there was a change in behaviour in the API that is causing this issue. The easy fix is to add an extra `/` at the end of the URL, but we will also revert to the previous behaviour soon.

**Comment by pomadchin** [comment]
@bosth yeah, i just simplified this line: https://github.com/planetlabs/planet-client-python/blob/16354d7567db154ba840f868f3a1e8b9373d5468/planet/api/client.py#L271 and doing direct calls to the planet API.

And thanks, your suggestion to add an extra `/` works perfect, could be a bit more challenging to fix this issue if we were using directly `get_assets_by_id` function from the planet client.

**Comment by bosth** [comment]
@pomadchin Great.

As far as we have seen, the client is unaffected - but it won't matter shortly as we'll revert to accepting both URLs.
