### ISSUE TITLE
KeyError when Multiple Assets Requested and Some Don't Exist

### ISSUE THREAD

**Issue by a-hubbard** [planetlabs/planet-client-python#163]
When using `--string-in id` to specify individual image IDs and the `--asset-type` flag to request multiple different assets, the client will crash with a Python `KeyError` if one of the requested assets does not exist for one of the requested images. It would be more desirable to print a warning and move on. This is because in some cases, such as when downloading SR products, the desired asset may exist for some images and not others, and the user does not have a way to anticipate this in advance.

The client will not crash or report an error if only one asset type is requested, e.g. when SR is the only product ordered. This is better, but a warning message would still be desirable.

**Comment by sarasafavi** [comment]
This should definitely be fixed; adding it to my near-future to-do list. Thanks @alfredhub for the report!

**Comment by sgillies** [comment]
I'm removing this from the 1.5.1 milestone. Not sure how to reproduce it and don't have a sense of where this bug would be (still kinda new to the code).

**Comment by jreiberkyle** [comment]
closing this as this bug is not in V2 and V1 is no longer in development
