### ISSUE TITLE
Docs referencing non-existing "await" method of Response class

### ISSUE THREAD

**Issue by Loopiezlol** [planetlabs/planet-client-python#164]
[Here](http://planetlabs.github.io/planet-client-python/api/reference.html#planet.api.models.Response.await) the response object is said to have the method `await` instead of `wait`, as defined [here](https://github.com/planetlabs/planet-client-python/blob/47f2db53e5ae7429f55a263fed83e97d8cf93a64/planet/api/models.py#L66).

I assume this happened as the wiki was not re-generated after [this commit](https://github.com/planetlabs/planet-client-python/commit/bbf63a7a85bbe071d6e8af2e94b89ba1a44be1ec#diff-edf2d4beca0941e2e0c5162c561c0f61).

**Comment by jreiberkyle** [comment]
fixed with update to release version 1.2.3 ([commit](https://github.com/planetlabs/planet-client-python/commit/e15b1ded53e310307da16d6788891898d78f2ace))
