### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by geom16011** [planetlabs/planet-client-python#166]
I tried to run the script in the example you provide
(https://planetlabs.github.io/planet-client-python/api/examples.html)

But i get the following error:
results = client.quick_search(request)
TypeError: quick_search() missing 1 required positional argument: 'request'

Any ideas?

**Comment by sarasafavi** [comment]
@geom16011 unfortunately I can't reproduce that problem, but I did notice a missing import in that script that will cause you trouble when outputting the results - thanks for helping us find that bug.

Double-check the `request` object that you're building on the line prior to the `client.quick_search(request)` call, it sounds like that's where you're missing something. After that, you can try running this `example_search.py` (which is the same as the example you linked, but includes the missing import line): https://gist.github.com/sarasafavi/66ad165d9dfcb7286c743eb6dd82bc58
