### ISSUE TITLE
support COGs in downloader

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#174]
Add support for activation and download of Cloud-Optimized Geotiffs in `downloader`. In the absence of support, COG download is achieved through an extended class, e.g. in https://github.com/planetlabs/notebooks/blob/master/jupyter-notebooks/temporal-analysis/crop-temporal.ipynb

**Comment by sgillies** [comment]
Unless I'm missing something, I think we can close this. Version 2 of the CLI/SDK is going to provide methods for waiting on activation instead of multi-purpose downloader.
