### ISSUE TITLE
Question - test_downloader.py - downloader.create() keyword arguments

### ISSUE THREAD

**Issue by SantiagoG** [planetlabs/planet-client-python#175]
Hello,

I appreciate if you can clarify what the keyword arguments to creating a Downloader instance mean:
downloader.create(
        client, no_sleep=True,
        astage__size=10, pstage__size=10, pstage__min_poll_interval=0,
        dstage__size=2)

activation stage size meaning?
polling stage size meaning?
min polling stage interval meaning?
download stage size meaning?

Thank you,
Santiago

**Comment by sgillies** [comment]
We're not developing the Downloader anymore and won't be adding more documentation.
