### ISSUE TITLE
Test coverage for ClientV1 orders methods

### ISSUE THREAD

**Issue by strixcuriosus** [planetlabs/planet-client-python#212]
We don't seem to have unit tests for orders related methods in `ClientV1`

It would be useful to create some unit tests with mocked API responses for these methods:
- `get_orders`
- `get_individual_order`
- `cancel_order`
- `create_order`
- `download_order`
- `download_location`

**Comment by strixcuriosus** [comment]
See https://github.com/planetlabs/planet-client-python/pull/210 for a description of an orders related bug found in the wild

**Comment by sgillies** [comment]
We're not doing this for V1 of the CLI.
