### ISSUE TITLE
Point 

### ISSUE THREAD

**Issue by geom16011** [planetlabs/planet-client-python#214]
Is it possible to use a point geojson and see if there are any Planet images or the geojson should be only polygon? 

Thank you in advance!

**Comment by sarasafavi** [comment]
@geom16011 that's a great question! It is indeed possible to search for imagery using a valid GeoJSON point feature (I encourage you to give it a try for yourself). The search will return any matching imagery that intersects with a given point.

As a point of interest, the `planet-python-client` uses Planet's Data API to conduct imagery searches; you can read more about how that API uses geometry in the docs here: https://developers.planet.com/docs/data/searches-filtering/#geometryfilter
