### ISSUE TITLE
mosaic download hangs on error while paging

### ISSUE THREAD

**Issue by ischneider** [planetlabs/planet-client-python#215]
If an unexpected error, 500 in this case (caused by a rare data misconfiguration), report from a client that the UI freezes.

The correct behaviour is probably to gracefully fail and log the trace-id to the user for error reporting. Another option might be to skip the error (a single quad in this case) and carry on but the internal handling of paging might make this trickier...

**Comment by sgillies** [comment]
We're not going to address this one for v1.
