### ISSUE TITLE
how to use CLI? where to install? 

### ISSUE THREAD

**Issue by mingxia-d** [planetlabs/planet-client-python#220]
I have install this package in my anaconda, but I can't find the CLI, and where to open this interface?

**Comment by sarasafavi** [comment]
hello @mingxia-d -- I recommend you take a look at the following resources to help you get started:

- you can find the complete documentation for this tool at https://planetlabs.github.io/planet-client-python/
- some examples for how you might perform different tasks using the CLI are at https://planetlabs.github.io/planet-client-python/cli/examples.html 
- and a video tutorial showing how to use the CLI to search for Planet data is at https://developers.planet.com/planetschool/get-started-with-planet-cli-searching-for-data/
