### ISSUE TITLE
Make "downloader" more usable

### ISSUE THREAD

**Issue by sarasafavi** [planetlabs/planet-client-python#225]
_(this is a general issue: in future we should capture specific usability issues here)_

In its struggle to be a one-size-fits-all solution to downloading different data from different Planet APIs, the current API "downloader" here is complicated & unwieldy. 

The fact that a script predating this library ([download.py](https://gist.github.com/sarasafavi/b6c1d29335bef3049566e5e11b212b53)) can still be found in use where users prefer not to deal with this library's downloader is a good sign that there's room for improvement.

**Comment by cholmes** [comment]
This is accomplished by async in V2.
