### ISSUE TITLE
Zip all CLI-based Orders to avoid incomplete downloads

### ISSUE THREAD

**Issue by sarasafavi** [planetlabs/planet-client-python#231]
see also: https://github.com/planetlabs/planet-client-python/issues/222

a non-deterministic bug occasionally results in incomplete downloads when Orders placed via CLI are not zipped: we should update the interface to force zipping for all orders in order to avoid this.

**Comment by jreiberkyle** [comment]
Force-zipping orders may cause us to run into #221 more often
