### ISSUE TITLE
implement cli auth key retrieval

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#252]
We have functionality for storing the API key via the CLI but no functionality for getting it. The primary use case for pulling the api key from the environmental variable is for use in a Docker container (as done in [planet notebooks](https://github.com/planetlabs/notebooks)). The api key is passed as a command-line argument when the Docker container is built. Add a CLI command for retrieving the api key so users and docs don't have to hard-code the path to the planet auth information.

So CLI commands for interacting with auth would be e.g. 
storing api key
`planet auth --init`

retrieving api key
 `planet auth --key` (explodes with a non-zero return if the planet key is not set, similar to `set +u` or `set +o unset`)

usage example:
`export PL_API_KEY=$(planet auth --key)`

_Originally posted by @jreiberkyle in https://github.com/planetlabs/planet-client-python/pull/240#discussion_r591825737_

**Comment by carl-adams-planet** [comment]
It should be noted that we want to phase out API keys as we move to Okta.  That phase-out may be long enough that it's not a foregone conclusion that API keys do not belong in SDK v2.
