### ISSUE TITLE
How to display all the available mosaics associated to my key ? 

### ISSUE THREAD

**Issue by 12rambau** [planetlabs/planet-client-python#272]
I would like to display all the available mosaics associated with my key but i only get the first page. I use the following code : 

```python

# launch api client 
from planet import api

client = api.ClientV1(api_key=key)

# list of the mosaics with numbers 
{i: m['name'] for i, m in enumerate(client.get_mosaics().get()['mosaics'])}
```

With this method I get the first 50 results and the one I'm looking for is 52. Did I miss a parameter ?

**Comment by jreiberkyle** [comment]
Hey @12rambau. Hmm... that is interesting behavior. There is no 'limit' parameter that you can change to get more than the 50 results you appear to be getting. However, there is a [`name_contains` parameter](https://github.com/planetlabs/planet-client-python/blob/ef8a27178d21316256ef8a5de6ee6d0758be981c/planet/api/client.py#L294) you can use to narrow down the scope, given you know the name of the 52nd mosaic you are looking for. Let me know what you get!

**Comment by 12rambau** [comment]
So I used it as a parameter to narrow down the search, so for my specific use case I solved it. BUT realizing that make me realize that I'm missing som mosaics when I create the mosaic list in my SEPAL Module (https://github.com/12rambau/planet-order/blob/50ae8c7193df30672cbc9214b4e9c8a674d2833e/component/scripts/planet.py#L57) I'm missing some if I'm using the client API. A possible workaround would be to come back to the good old request system : 

```python
SESSION = requests.Session()
SESSION.auth = HTTPBasicAuth(PLANET_API_KEY, '')
response = SESSION.get(basemaps_url, params={'_page_size': 1000})

orders = response.json()["mosaics"]
for order in range(0,len(orders)):
     print(orders[order]["name"])
```

But I prefer the client object than using that. I'll dig in your code to see if I can add the `_page_size`parameter somewhere in the url.

**Comment by 12rambau** [comment]
Any news ? It's actually a problem for every user using the NICFI contract from FAO we all have too many mosaics. I'm happy to contribute (it's the main point of being open source right?) but I didn't receive any feedback for my latest PR, that I'm happy to modify to comply to any of your requests.

**Comment by joferkington** [comment]
In general, for all Planet APIs, the responses are paginated. Note that there's a `_next` link in that response that contains the next batch of mosaics. Increasing `page_size` is not a good solution for many reasons.  

Instead, use the existing methods to iterate over the responses similar to what `planet mosaics list` does.  In general, the python client isn't set up for use as a python library, so it's a bit cumbersome to use the client methods.  

For example:

```
import planet.api

def list_mosaics(client):
    mosaics = client.get_mosaics()
    while True:
        for item in mosaics.get()['mosaics']:
            yield item
        mosaics = mosaics.next()
        if mosaics is None:
            break

client = planet.api.ClientV1()
for info in list_mosaics(client):
    print(info['name'])
```

**Comment by 12rambau** [comment]
thank you very much for your answer, I'll close my pull request then and adapt your solution to my needs ;-)
