### ISSUE TITLE
remove prefixes from code in rendered markdown

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#275]
Removing the `>>>` and `...` line prefixes from code snippets would make it easier copy from the rendered markdown. However, these prefixes are currently included to enable doctests. Consider other options for testing code snippets e.g.
- https://pypi.org/project/exdown/ (first-glance favorite)
- https://github.com/tmarktaylor/phmdoctest

Ref:  https://github.com/planetlabs/planet-client-python/pull/271#discussion_r617731380_

Also, rework doctests so that tests don't fail on auth.

**Comment by cholmes** [comment]
closing in favor of #338
