### ISSUE TITLE
look into ways of not duplicating things in README.md and docs/index.md

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#277]
Looking into the issue raised around this in mkdocs (https://github.com/mkdocs/mkdocs/issues/321#issuecomment-70106615), it looks like our options are linking to `docs/README.md` a stub root `README.md` or duplicating things.

REF: https://github.com/planetlabs/planet-client-python/pull/271#discussion_r621712367_

**Comment by cholmes** [comment]
I think this may no longer be relevant? As our doc system has moved a bit.
