### ISSUE TITLE
 support stdin as input to cli

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#286]
Support stdin in the cli via the `-` symbol.

Follow the convention used by [Click](https://click.palletsprojects.com/en/7.x/arguments/#file-arguments)
```
$ inout - hello.txt
hello
^D
$ inout hello.txt -
hello
```

and [rasterio](https://rasterio.readthedocs.io/en/latest/cli.html#mask)

`$ rio mask input.tif output.tif --crop --geojson-mask - < input.geojson`

also (from #55)

`$ cat region.geojson | rio mask input.tif output.tif --geojson-mask -`

e.g. 

`$ planet orders create <specify name, id, product, bundle> --clip - < clip.geojson`

**Comment by cholmes** [comment]
May be covered by latest proposals.
