### ISSUE TITLE
consider using cligj for parsing geojson arguments

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#291]
[cligj](https://github.com/mapbox/cligj/blob/master/cligj/features.py) contains many tools for parsing GeoJSON inputs and is used by Rasterio. Consider using this library for parsing GeoJSON in the CLI.

**Comment by jreiberkyle** [comment]
May be related to, or resolve #286

**Comment by cholmes** [comment]
We decided this is not the direction we want to go.
