### ISSUE TITLE
More generic search options

### ISSUE THREAD

**Issue by joshtennefoss** [planetlabs/planet-client-python#30]
Ability search to take more generic inputs, like bounding boxes, for example like:

geocode -o geojson 'iowa' | jq .bbox | planet search

**Comment by kapadia** [comment]
@joshtennefoss are you suggesting the format that geojson stores the bbox parameter? e.g.

    $ rio bounds 20150712_094442_090c_analytic.tif --bbox
    [13.07778167237727, 32.823663318333196, 13.277200022341434, 32.95744007495531]

If so, why not just pipe the entire geojson to `planet search` rather than parsing with `jq`?

**Comment by kapadia** [comment]
Looks like the Geocoder module support geojson:

    $ geocode "Berkeley, CA" --output geojson | planet search

**Comment by ischneider** [comment]
While Geocoder does support geojson output, for regions (e.g. Kansas), this does not include a polgon, only a point (centroid?). A bbox is provided as a property but not in a 'standard' format: http://geojson.org/geojson-spec.html#bounding-boxes

For example, the output of searching for Kansas includes:
```json
"bbox" : {
      "southwest" : [
         36.993125,
         -102.0517562
      ],
      "northeast" : [
         40.003095,
         -94.5882048
      ]
}
```

One approach might be to add support for reading a standard bbox from the input geojson. Or even a `bbox` option. Until the upstream output conforms, reformatting could be achieved with jq:

`geocode --output geojson kansas | jq '.bbox.southwest + .bbox.northeast'`

With the (newly) proposed `bbox` option and using the stdin convention (@ specifies a file and @- specifies stdin) adopted by the js client, this could look like:

`geocode --output geojson kansas | jq '.bbox.southwest + .bbox.northeast' | planet search --bbox @-`
