### ISSUE TITLE
update `orders_create_and_download_multiple_orders.py` example

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#309]
`orders_create_and_download_multiple_orders.py`, which exists in the `examples/` folder, is out of date and needs to be updated to use the `order_request` module

**Comment by jreiberkyle** [comment]
Related to #316

**Comment by kevinlacaille** [comment]
Looks like [this commit](https://github.com/planetlabs/planet-client-python/pull/318/commits/3327fb529811a6d55f1186df4139913c76d88590) to PR #318 will close this issue.
