### ISSUE TITLE
change polling output to a progress bar

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#310]
Polling can fill up the stdout with all its status messages. Change the status to an updating progress bar. Move status messages to logging.

**Comment by kevinlacaille** [comment]
May I recommend a really fun progress bar called [alive-progress bar](https://github.com/rsalmei/alive-progress)?

**Comment by jreiberkyle** [comment]
@kevinlacaille thanks for that - what a cool progress bar! We already are using tqdm so I'll stick with that. always good to know what's out there!
