### ISSUE TITLE
Have the authentication run in background, if instance isn't initialized

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#317]
**Issue:** If a user were to run a Planet API (i.e., `planet orders download my-order-id`) without first running `planet auth init`, it would throw an error.

**Proposal:** Have the authentication API run in the background the first time a user queries a Planet API.

For instance, have the client recognize that the user hasn't run `planet auth init`, the prompt for them for their credentials (i.e., email and password).

**Alternative:** If the user hasn't run `planet auth init` before running a Planet API, have the client echo back a useful error message such as: “User’s credentials (Planet login email & password) must be provided to run Planet APIs. Run `planet auth init` to initialize your Planet client.".

**Comment by JSee98** [comment]
Hey @kevinlacaille, I'd like to pick this issue up next, i.e. once I've close my current PR.
My solution is to update CLISessions object (https://github.com/planetlabs/planet-client-python/blob/main/planet/cli/session.py#L11) to check if the auth went through successfully and suggest a login for the user (your first suggestion).

I think it would be a nice addition as compared to simply returning a error (though that is simpler to implement)

**Comment by JSee98** [comment]
Hi @kevinlacaille, could you assign this to me if its still unassigned?

**Comment by kevinlacaille** [comment]
Hi, @JSee98!

Thank you for your interest and being keen on continuing to contribute to the Python client! This ticket is pretty out of date and isn't something we're hoping to implement anymore.

If you'd like a quick and easy ticket, #980 would be awesome to fix!

Cheers,

Kevin

**Comment by JSee98** [comment]
Hey @kevinlacaille,

Sure I can pick the suggested issue, however, just wanted to know if you have any other tasks as well which are more code-heavy or something that might help me get more accustomed to the code. But still wouldn't mind picking #980

**Comment by JSee98** [comment]
Also, raised the PR for #980 (https://github.com/planetlabs/planet-client-python/pull/999)
