### ISSUE TITLE
Proposal: Filesystem check by default

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#329]
**Backstory / Insight:** V1 had some issues with some files not being downloaded and it was never checked that all files existed. About 20% of the time there was data missing.

**Proposal:** Check to see if all files in an order were downloaded after the download has occurred. If `overwrite = True`, do not check the files that already have been previously downloaded for that order, only check newly downloaded data.

Asess the:
- cost of writing said feature;
- additional run time;
- value compared to the `--check` option (md5 checksums).

**Comment by jreiberkyle** [comment]
This is not needed. We have integration tests (mocked server) that check the expected files are downloaded. There is no need to add code that checks this within the function itself. If this is identified as a problem integration tests don't take care of, we can investigate full on QA/QC testing.
