### ISSUE TITLE
Client download not handling SSL cert file

### ISSUE THREAD

**Issue by AW313** [planetlabs/planet-client-python#332]
Hi,
I'm trying to access the API Client, works from home and downloads images, but from the office, which has a firewall we get an SSL error issue. We can get around this on standard request.get() with verify = certification file. 
For the Planet client we had to alter the code with:

from planet.api import dispatch
dispatch.USE_STRICT_SSL=/c/path/to/certificate_file

This allows the Planet Client to function with pulling searches, status etc, except for when running the 
client.download(assetlink, write_to_file(/folder/) )
 This will pass but does not actually download a file or output any errors. 

If you change the download client to return an object and explore this, it shows the error thats not being handled by the client download part. please help

![offn](https://user-images.githubusercontent.com/75986854/139237178-cfa8a84a-8711-4738-8d3d-e855b0e64002.png)
![onN](https://user-images.githubusercontent.com/75986854/139237185-44ce2b57-4c97-4ce2-922b-b8c2d0173209.png)

**Comment by josephble** [comment]
@AW313, could you please share which version of the SDK you are using?

**Comment by AW313** [comment]
win10
Python 3.7.11
planet 1.4.7
click 7.1.2
pywin32 228
requests 2.26.0
requests-futures 0.9.7

We have found firewall workaround using a docker. cheers,
