### ISSUE TITLE
write design document

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#345]
Add a design document (for example, DESIGN.md) that explains in ~1 page the design goals of the project (reflect with 100% fidelity the existing APIs? provide a different interface to the same features?), main abstractions of the project, why we chose them among alternatives, and organization of the code.

This has multiple applications:
- potent point for stakeholder input
- drive design decisions
- keep development focused
- help new contributors orient to the project

**Comment by jreiberkyle** [comment]
Part of implementation design should include intentionality around how we design V2 to minimize effort in syncing assets/itemtypes/bundles. This could be addressed with: pull as much as possible from the API specs.

**Comment by jreiberkyle** [comment]
@sgillies could you expand on "main abstractions of the project, why we chose them among alternatives..."?

Also, what are your thoughts on discussing organization of the code here vs in the CONTRIBUTING doc?

**Comment by sgillies** [comment]
@jreiberkyle by abstractions, I mean the "nouns" in the design and what we can do with them. For example, Python's xml module has both tree-based (etree) and event-based (sax) parsing abstractions. For this SDK, is a user working with requests and responses, or working with Orders and Searches? Or maybe a different abstraction all together?
