### ISSUE TITLE
Quantify 'accurate and complete documentation' required for initial release

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#353]
The scope for SDK initial release includes 'accurate and complete documentation'. Quantify what this is so we have an achievable goal.

The documentation of the SDK should aim at SDK specifics, leaving documentation specific to our products and geospatial concepts in general to be covered by the DevCenter. Aim for documentation similar to [gcloud](https://cloud.google.com/sdk/gcloud/reference) and aws ([CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and [SDK](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html)), which are similar and popular cloud SDKs.

**Comment by cholmes** [comment]
blocked by #479
