### ISSUE TITLE
Update download order interface

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#365]
Update the CLI interface to match the following, and change the API interface accordingly:

```
Usage: planet orders download [OPTIONS] ORDER_ID

  Download order

Options:
  --directory DIRECTORY  Root directory for file download.
  --overwrite            Overwrite files if they already exist.
  --help                 Show this message and exit.
```
**NOTE:** make sure to remove short options

**Comment by mkshah605** [comment]
@jreiberkyle the CLI interface currently has a "--quiet" option. Will this be incorporated into V2 in a different way? Just want to be sure before I remove it to match the format above.

**Comment by jreiberkyle** [comment]
Kevin is working on the —quiet option. You can sync with him to get the details.

**Comment by mkshah605** [comment]
Note: in the description above, "Root" changed to "Base". This change is reflected in the docs as well.
