### ISSUE TITLE
Implement CLI quiet option, use in download order

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#369]
- Implement a new CLI option, `--quiet`, which will disable all reporting and store the value in the CLI context.
- Use the quiet flag in `planet orders download OID` to disable progress bar reporting if specified as `planet --quiet orders download OID`

Usage interface showing `--quiet` flag
```
Usage: planet [OPTIONS] COMMAND [ARGS]...

  Planet Command Line Interface

Options:
  --verbosity [warning|info|debug|none]
                                  Logging verbosity level.
  --quiet                         Disable all reporting.
  --version                       Show the version and exit.
  --help                          Show this message and exit.

Commands:
  auth    Commands for working with Planet authentication
  data    Commands for interacting with the Data API
  orders  Commands for interacting with the Orders API
```

Blocked by #362

**Comment by kevinlacaille** [comment]
Not entirely sure what is needed here, but when I run `planet orders download my-oid`, there is no longer reporting in my command line (i.e., progress bar reporting is disabled). Can I close this issue? @jreiberkyle

**Comment by jreiberkyle** [comment]
Hmm.. I believe the desired functionality is that the progress bar reporting is enabled by default and then is disabled when we run `planet --quiet orders download <OID>`

**Comment by jreiberkyle** [comment]
ahh, I see the confusion. Yes, the plan is to move the `--quiet` flag to right after planet. I will update the ticket description. Apologies, this was unclear.
