### ISSUE TITLE
Change SDK author to DevRel

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#374]
The SDK is supported by the devrel team, so change the author/email entries to the devrel team.

**Comment by sgillies** [comment]
What I've done is left you @jreiberkyle as Author :pray:, deleted author_email and then added maintainer and maintainer_email fields. This is what the Numpy and Shapely projects have done.

Also, I bumped the version to 2.0a1 and added a brief entry to the change log.
