### ISSUE TITLE
Update list order interface, change limit behavior

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#380]
- Update the CLI list order interface to match the interface given below
- Change the behavior of the limit option (in the API as well as the CLI). The limit option should to default to 100, and when user sets it to 0 it should not limit at all.
- Change the output to output each order individually in a sequence. If --pretty is specified, pretty-print each order json blob

```
Usage: planet orders list [OPTIONS]

List orders

This command outputs a sequence of the returned order descriptions.
If --pretty is specified, each order description is pretty-printed.

Options:
  --state TEXT     Filter orders to given state.
  --limit INTEGER  Maximum number of results to return. Default is 100. A
                   value of 0 means no maximum.
  --pretty         Format JSON output.
  --help           Show this message and exit.
```

**Comment by kevinlacaille** [comment]
I think `--state TEXT` introduces ambiguity, as it's not immediately obvious that the options are and doesn't tell them where to find the options. Although it's not as clean, I propose we keep it as a `click.Choice()`, which will indicate the options to the user (i.e., `queued|running|failed|success|partial|cancelled`). Thoughts @jreiberkyle @cholmes @sgillies ?

**Comment by kevinlacaille** [comment]
I propose we change `--state TEXT` to `--state` + a list of all choices available to the user given by `click.Choice()`. i.e., `--state [queued|running|failed|success|partial|cancelled]`.

**Comment by kevinlacaille** [comment]
I think we can get away with only updating the behaviour of the limit option in API (instead of both API and CLI), as the CLI calls the API.

CLI code (`planet.cli.orders.list()`)
```
async with orders_client(ctx) as cl:
    orders = await cl.list_orders(state=state, limit=limit)
    orders_list = [o async for o in orders]
```

As the CLI calls `cl.list_orders()`, I believe we'd only need to influence the behaviour of the limit option in said function (`planet.clients.orders.OrdersClient.list_orders()`)

**Comment by jreiberkyle** [comment]
I agree with using Click.choice for the option in the cli. The api can (and should) also check to ensure that the provided argument is one of the list of valid choices. That list should be an environment variable in the client module and be used to populate click.choice.
