### ISSUE TITLE
change orders CLI to accept stdin for ORDER_ID argument

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#383]
Currently, `planet orders` group `get`, `download`, and `cancel` CLI commands only accept a UUID for the ORDER_ID argument. Expand this to accept `-`, which reads from stdin (and ensure that the stdin is a UUID).

Update CLI interface documentation accordingly.

Also document the following use case:

User Story: As a CLI user I would like to create an order, wait for it to be ready to download, then download the order. 
```
$ planet orders create –like order_description.json \
    | jq -r ‘.id’ | planet orders wait - \
    | jq -r ‘.id’ | planet orders download -
<ANSI wait and download status reporting>
```

**Comment by sgillies** [comment]
@jreiberkyle that pattern really shines with programs that are filters and take multi-line input. But planet-orders-create only creates a single order, right? And the other commands only accept a single order id.

And since the order id is set in stone early on, I think we can do this without reading order id from stdin for now.

```
$ orderid=$(planet orders create –like order_description.json | jq -r '.id') \
    && planet orders wait $orderid \
    && planet orders download $orderid
```

**Comment by jreiberkyle** [comment]
Thanks for this discussion, @sgillies - I can't believe it slipped past my attention back in Feb. Using the shell to set and access `orderid` is an elegant solution. One that isn't immediately obvious to novice to intermediate level shell users, so we probably want to document it somewhere close to the commands.

Your point about not requiring `jq` is a valid one. For now, let's lean on `jq` and post-release let's consider cost/benefit of removing the `jq` dependence.
