### ISSUE TITLE
Implement --search-id support in orders request

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#388]
Blocked by #509

Implement support for the --search-id parameter in order creation in the orders API and CLI.

CLI Interface
```
Options:
 ...
  --search-id TEXT  ID of search from which to populate item IDs.
 ...
```
Usage (in CLI documentation and/or usage guide)
```
  When creating an order description from scratch, the following options are
  required: --name, --bundle, and one (and only one) of --id or --search-id.

 ...

  To create a clipped order using stdin:

  $ planet orders create \
      --name test_order \
      --bundle analytic \
      --id 20200922_183724_23_106a,20200922_183722_17_106a \
      --clip - < aoi.geojson

  Accomplishing the same thing but with a search id instead of item ids:

  $ planet orders create \
      --name test_order \
      --bundle analytic \
      --search-id 897802165e8d4bd587e342a4b399eda6 \
      --clip - < aoi.geojson

 ...
 
  Finally, it may be desirable to create a test order and, once satisfied,
  populate the order with item ids from a saved search. To do this, use --like
  and --search-id:

  $ planet orders create \
      --like 49b8d32e-2fba-4924-bd38-f7344aa48d91 \
      --search-id 897802165e8d4bd587e342a4b399eda6
```

**Comment by jreiberkyle** [comment]
@cholmes This is not strictly required for full usage of Orders API. It is an add-on "bonus" feature. It could be argued that this does not need to be in an MVP. Also, this requires the Data API to be implemented to get ids from a search ID. I'm putting this in the Data MVP milestone but also want to note that we could push it back farther.

**Comment by cholmes** [comment]
So I think I'm inclined to remove this option. I came upon a way to use the id's from a data search in a one-liner, see https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli-tutorial/#bringing-it-all-together Which feels a lot easier to use than creating a whole search and then using that for input. I could invent some obscure use cases where you might want to do this, but I think the main one is covered by the in-line searching. 

@jreiberkyle - let me know if you agree, and I can do a PR to remove it from the design doc.

**Comment by jreiberkyle** [comment]
@cholmes the one-liner looks great, let's go that route and cut this feature. We can always revisit if it is causing users undue troubles.

**Comment by cholmes** [comment]
Closing this, as the one-liner referenced above seems to work well enough.
