### ISSUE TITLE
Determine Subscriptions CLI interface

### ISSUE THREAD

**Issue by sgillies** [planetlabs/planet-client-python#423]
In a doc for internal review by API team and Product. Specifically, it will enumerate the commands, describe their inputs and outputs, and flag some implications for implementation.

**Comment by cholmes** [comment]
Results of this work are available at https://github.com/planetlabs/planet-client-python/discussions/443

**Comment by cholmes** [comment]
Clean up comments and put in CLI interface doc, and ideally port over to public discussion.

**Comment by sgillies** [comment]
Comments and related sections of text are resolved. @jreiberkyle can you copy it over to the main doc?

**Comment by jreiberkyle** [comment]
@sgillies I’m off today but I gave you permissions. Go for it!

**Comment by sgillies** [comment]
Done.
