### ISSUE TITLE
Image Download Issues via V1 Data CLI

### ISSUE THREAD

**Issue by mkshah605** [planetlabs/planet-client-python#426]
The following image IDs don't properly download using the CLI. The progress monitor goes for 3-4 seconds, and then stops, and no images are downloaded. These images ARE downloadable using the API/requests.

Image IDs:
- 20160831_180302_0e26
- 20170623_180038_0f34

CLI code currently not working:

`!planet data download --item-type PSScene --dest data --asset-type ortho_analytic_4b, ortho_analytic_4b_xml --string-in id 20160831_180302_0e26`

`!planet data download --item-type PSScene --asset-type ortho_analytic_4b, ortho_analytic_4b_xml --dest data --string-in id 20170623_180038_0f34`

**Comment by ischneider** [comment]
Closing due to V1 deprecation.
