### ISSUE TITLE
Create example tests for Subscriptions CLI

### ISSUE THREAD

**Issue by sgillies** [planetlabs/planet-client-python#430]
I'm proposing to create at least a couple tests for the Subscriptions CLI and mark them as expected to fail. Before we have our first pre-release we'll hook them up to the client module, remove the xfail marker, and get them to pass.

cc @jreiberkyle @kevinlacaille @mkshah605 .

**Comment by jreiberkyle** [comment]
this sounds excellent @sgillies !

**Comment by sgillies** [comment]
I took this a little further in #571 and worked backward to uncover the rough shape of the future production Subscriptions  python client (python module functions, not CLI).
