### ISSUE TITLE
Add checksum match to download order

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#432]
Add checksum match to download order.

Update the CLI interface to match the following, and change the API interface accordingly:

```
Usage: planet orders download [OPTIONS] ORDER_ID

  Download order

  If --checksum is provided, the associated checksums given in the manifest
  are compared against the downloaded files to verify that they match.

Options:
  --checksum [MD5|SHA1]  Verify that checksums match.
  --directory DIRECTORY  Root directory for file download.
  --overwrite            Overwrite files if they already exist.
  --help                 Show this message and exit.
```

Implement checksum match verification for download order for the CLI and API. In the API, add a new parameter, `checksum` to `orders.download_order()` and implement the functionality to check the checksum of the downloaded files against the downloaded manifest. Add a new exception that is thrown upon match validation failure. In the CLI, pass on the `checksum` variable and handle the thrown exception.

**Comment by mkshah605** [comment]
@jreiberkyle the manifest json files have MD5 and SHA256 keys. Do we still want SHA1 to be an option here, or should we just keep it MD5?

**Comment by jreiberkyle** [comment]
You can just update the option to SHA256 instead of SHA1
