### ISSUE TITLE
Create example tests for Data CLI

### ISSUE THREAD

**Issue by sgillies** [planetlabs/planet-client-python#433]
I'm proposing to create at least a couple tests for the Data CLI and mark them as expected to fail. Before we have our first pre-release we'll hook them up to the client module, remove the xfail marker, and get them to pass.

cc @jreiberkyle @kevinlacaille @mkshah605 .

**Comment by jreiberkyle** [comment]
this sounds excellent @sgillies. thank you! (btw may want to change subscriptions -> data in the ticket desc)
