### ISSUE TITLE
Review initial OpenID Connect auth PR and give feedback on it

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#450]
There is an initial PR up for OpenID Connect at https://github.com/planetlabs/planet-client-python/pull/448 It'd be good to review it and give feedback on what is needed to get it into a state to merge. This will get us integration with Planet's new auth system, which would be good to support.

**Comment by jreiberkyle** [comment]
FYI @carl-adams-planet

**Comment by cholmes** [comment]
This work at Planet is on hold, so closing this, can make a new issue when this is relevant again.
