### ISSUE TITLE
Use the same verbose/quiet mode as python, pip, mercantile, rasterio

### ISSUE THREAD

**Issue by sgillies** [planetlabs/planet-client-python#466]
@kevinlacaille following up on #439, I'd like to see this project use the same pattern as python, pip, mercantile, rasterio (and others). That is to say, our default [logging level](https://docs.python.org/3/library/logging.html#logging-levels) should be WARNING (30), and `planet -v` should change this to INFO (20), and `planet -vv` should change it to DEBUG (10). Similarly `planet -q` should change it to ERROR (40).

If we follow mercantile (see https://github.com/mapbox/mercantile/blob/main/mercantile/scripts/__init__.py#L57-L62) we can replace our more complex existing code with a more simple subtraction statement.

Example command:

```python
@click.group()
@click.pass_context
@click.option("--verbose", "-v", count=True, help="Increase verbosity.")
@click.option("--quiet", "-q", count=True, help="Decrease verbosity.")
@click.version_option(version=planet.__version__)
def main(ctx, verbose, quiet):
    """Planet API Client

    Parameters:
        ctx: context object
        verbose: number of levels of verbosity increase.
        quiet: number of levels of verbosity decrease.

    """
    ctx.ensure_object(dict)
    verbosity = verbose - quiet
    ctx.obj["verbosity"] = verbosity
    _configure_logging(verbosity)

def _configure_logging(verbosity):
    """configure logging via verbosity level, corresponding
    to log levels warning, info and debug respectfully.

    Parameters:
        verbosity: user input for verbosity.
    Raises:
        click.BadParameter: on unexpected parameter input
        
    """
    log_level = max(10, 30 - 10 * verbosity)
    logging.basicConfig(
        stream=sys.stderr,
        level=log_level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
```

Example test:

```python
@pytest.mark.parametrize(["opts", "verbosity"], [([], 0), (["-v"], 1),
                                                 (["-vv"], 2), (["-q"], -1)])
@patch("planet.cli.cli._configure_logging")
def test_new(mock_config, opts, verbosity):
    """."""

    @click.command()
    @click.pass_context
    def test(ctx):
        assert ctx.obj["verbosity"] == verbosity

    cli.main.add_command(test)

    runner = CliRunner()
    result = runner.invoke(cli.main, opts + ["test"])
    assert result.exit_code == 0
    mock_config.assert_called_once_with(verbosity)
```

Testing that the log level is set within the CLI runner is complicated (too complicated)! But we don't need to do it for a unit test. Asserting that _configure_logging() gets called is enough. And _configure_logging will be unit tested, too, so we'll be sure that the logger is getting configured properly.

**Comment by kevinlacaille** [comment]
I do like this simplicity and **thank you** for the example code and test, that's so helpful. 

I'm on board with this, but I know @jreiberkyle was hoping to remove short forms (i.e., no -v/-q).

**Comment by jreiberkyle** [comment]
How we handle verbosity has already been decided in the proposal stage of the CLI and it is based on gcloud and aws being our primary community. Mansi just completed work in implementing it. At this stage of development, please refer to and defer to the accepted CLI interface prior to proposing work.
