### ISSUE TITLE
handle 502 better

### ISSUE THREAD

**Issue by ischneider** [planetlabs/planet-client-python#48]
as reported by a client seeing occasional 502 responses

either:
- requests should be configured to retry (if not already)
- client should attempt a delayed retry

it seems reasonable to allow the user to configure the behavior (ignore or retry X times then fail) as persistent server-side API errors are likely important in their workflows (e.g. understanding why no data showed up)

**Comment by bosth** [comment]
Note that the following triggers a 502 error:

`planet search --where camera.gain gt 100.0`

But this doesn't:

`planet search --where camera.gain gt 100`

**Comment by ischneider** [comment]
Thanks @bosth - this specific issue has been resolved for any float/int fields.

Sometimes the 502 is a genuine problem like a timeout, other times it is a backend failure.

**Comment by sgillies** [comment]
We're not going to make any more Python 2.7-compatible enhancements to this project. See the note in the https://github.com/planetlabs/planet-client-python/milestone/2.
