### ISSUE TITLE
handle API error messages better on client

### ISSUE THREAD

**Issue by ischneider** [planetlabs/planet-client-python#49]
by default, format API responses for better readability. allow a flag to get the raw error as JSON.

Example:

``` json
{"message": "Query parameter validation failed", "errors": [{"field": "intersects", "message": "GeometryCollections are currently unsupported"}]}
```

In this case, the provided AOI is invalid. Ideally, the error 'translator' would see that intersects field is bad and (since we built the query from the provided API) note the provided AOI is invalid with the reason. If we cannot determine a more specific message, we can default to formatting like so:

```
Query parameter validation failed:
Field 'intersects' invalid:  GeometryCollections are currently unsupported
```

Also see #24 (re: raw error flag)

**Comment by sgillies** [comment]
We're not going to make any more Python 2.7-compatible enhancements to this project. See the note in the https://github.com/planetlabs/planet-client-python/milestone/2.

In v2, we will use the builtin exception chaining in Python3, catch API exceptions with their JSON error messages and raise another error with the original error as its context. No formatting, no loss of information.
