### ISSUE TITLE
Implement CLI command: planet data search-update

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#497]
implement `planet data search-update`

## Interface

planet data search-update [OPTIONS] SEARCH_ID NAME ITEM_TYPES FILTER

Update a saved search with the given search request.

**Arguments:**
SEARCH_ID - string. A saved search identifier.
NAME - string. The name to give the saved search.
ITEM_TYPES - string. Comma-separated item type identifier(s).
FILTER - string. A full JSON description of search criteria. Supports file and stdin.

**Options:**
--daily-email - flag. Send a daily email when new results are added.
--pretty - flag. Pretty-print output

**Output:**
A full JSON description of the updated search.

**Comment by cholmes** [comment]
Depends on #509

**Comment by jreiberkyle** [comment]
closed by #852
