### ISSUE TITLE
implement data api search functions

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#509]
implement the following data api search functions:
* list_searches
* delete_search
* get_search
* update_search
* run_search

**Comment by mkshah605** [comment]
list_searches = `search-list`
delete_search = `search-delete`
get_search =` search-get`
update_search = `search-update`
run_search = `search-run`

**Comment by jreiberkyle** [comment]
@mkshah605 the interface for these fcns was defined in #527

**Comment by cholmes** [comment]
I think #462 closes this? Can you confirm @jreiberkyle ?
