### ISSUE TITLE
More defaults & heuristics to help orders?

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#523]
When I was making the quickstart in #472 I was struck how many options I needed to supply to create an order:

```
$ planet orders create --name my-first-order --id <scene-ids> --item-type PSScene --bundle visual
```

It seems like many of those we could have reasonable defaults or heuristics for. Like could we get all the way to:

```
$ planet orders create --id <scene-ids>
```

I feel like Explorer manages to figure out the item-type from the id, so hopefully we could have some way to just figure it out too. That to me is one that would help - I often have to look up the item-type to make sure I have it right. 

We could also try to give a default name to the order, perhaps like a date-stamp and user name or something? I often struggle to come up with some name to use. And we could also come up with some default bundles, perhaps by item-type. 

With #366 this should all just go in the request creation.

**Comment by tbarsballe** [comment]
Now that Orders API supports wide variety of data sources - from Scenes to PVs to Basemaps - sensible defaults are quite a bit more difficult to determine.
The underlying sentiment of "make it easier to use orders" is still applicable, but this particular solution isn't
