### ISSUE TITLE
signal handling broken on 2.7 with requests_futures

### ISSUE THREAD

**Issue by ischneider** [planetlabs/planet-client-python#53]
Ctrl-C has no effect and async tasks proceed. See: https://github.com/agronholm/pythonfutures/issues/25

Unless we can work-around with requests_futures or the futures backport is fixed , might need to use a multiprocessing approach.

**Comment by kapadia** [comment]
@ischneider I just ran into a similar problem with a client i'm writing for the Sentinel archive. It uses `requests`, no futures, and SIGINT also doesn't work as expected.

Within `planet/scripts/__init__.py`, it might be worth appending the following to the top of the script.

```
import signal

def signal_handler(signal_code, frame):
    sys.exit(0)

signal.signal(signal.SIGINT, signal_handler)
```
