### ISSUE TITLE
Content Plan Task--EoL this project wiki

### ISSUE THREAD

**Issue by JuLeeAtPlanet** [planetlabs/planet-client-python#531]
End-of-life the GitHub wiki content for V2, and rely on the readme, the contributing, the changes, and the published documentation to convey information published at the wiki in 2017.[1]

Go to the [wiki](https://github.com/planetlabs/planet-client-python/wiki).

Expected: updated content or no content

Actual: Old content

[1] See [SSoT section in Content Plan](https://github.com/planetlabs/planet-client-python/blob/main/design-docs/content-plan.md#ssot)

**Comment by JuLeeAtPlanet** [comment]
explain how to comm in contributing and search for refs to wiki before removing wiki pages

**Comment by JuLeeAtPlanet** [comment]
Removed old content pages. Cannot "turn off" page, as I don't have access to "Settings" in this project. https://docs.github.com/en/communities/documenting-your-project-with-wikis/disabling-wikis

**Comment by JuLeeAtPlanet** [comment]
Assigning to @cholmes to re-assign, turn off wiki, or give me access to "Settings."

**Comment by cholmes** [comment]
This looks to be done.
