### ISSUE TITLE
Content Plan Task--Code snippets

### ISSUE THREAD

**Issue by JuLeeAtPlanet** [planetlabs/planet-client-python#540]
For the sake of this document, a code snippet is a block of code in the documentation that provides a code example of how to use the command being documented. A code snippet is not the output of the source code in the SDK. A code snippet for the SDK is not the CLI string.

Provide a code snippet for each call, using real-life terms (i.e., not foo & bar).

Provide a CLI cheat sheet (separate from the SDK) with examples using real-life terms. (See, for example, [The gcloud CLI cheat sheet](https://cloud.google.com/sdk/docs/cheatsheet).)

**Comment by tbarsballe** [comment]
#540 better captures what we actually want for documentation, closing this as wontfix
