### ISSUE TITLE
Content Plan Task--Document features list (architectural decisions & capabilities)

### ISSUE THREAD

**Issue by JuLeeAtPlanet** [planetlabs/planet-client-python#542]
Describe the architecture to the extent it’s helpful to the user, and from the user’s perspective. Explain what capabilities we’re providing in the SDK & CLI. For example:

The SDK and CLI provide low-level clients to the core Planet APIs, with a one-to-one match between function calls and API endpoints. The SDK and CLI also provide:

* Retry logic
* Some pre-validation of inputs
* Helper functions for creating JSON request arrays
* Some state management
* Managing paged responses
* Download file checksum validation

**Comment by cholmes** [comment]
In content-planet.md under design docs.
