### ISSUE TITLE
Content Plan Task--Restart the changes.txt file

### ISSUE THREAD

**Issue by JuLeeAtPlanet** [planetlabs/planet-client-python#545]
The [current changes.txt](https://github.com/planetlabs/planet-client-python/blob/v2/CHANGES.txt) file is out of date.

Remove the changes.txt file for version 2.0, as this is a major release and does not require a dot-release changes file.

Consider publishing this data in the SDK documentation.

**Comment by cholmes** [comment]
closed by #545

**Comment by jreiberkyle** [comment]
@JuLeeAtPlanet Sara requested that I take this task over. To help me out, can you elaborate on what you'd like to accomplish here? We do want to continue with having a changelog in the repo, yes? Just remove V1 stuff?

**Comment by JuLeeAtPlanet** [comment]
I would expect that the changes.txt file restart at 2.0.0.

**Comment by jreiberkyle** [comment]
Upon discussion with @JuLeeAtPlanet, we decided there is no need to change the changes.txt file. There is precedent for keeping entries from the beginning (fiona and geopandas) and it would be helpful to keep entries before 2.0.0 release for all users of the alpha and beta releases. The task now is to update the content plan.
