### ISSUE TITLE
Content Plan Task--Call out cost associated with SDK calls vs other methods

### ISSUE THREAD

**Issue by JuLeeAtPlanet** [planetlabs/planet-client-python#548]
Are there any batch calls or “quick” calls that could inadvertently incur costs?

Call out what costs are being generated by using the SDK against the account in a considerations section.

Call out recommendations for batch & bulk routines (maybe in a considerations setion).

Make clear that calls will hit the quotas, just like the APIs.

**Comment by cholmes** [comment]
Let's at least discuss this and decide what to tell users for beta.1

**Comment by cholmes** [comment]
Sure. I think this can be pretty simple though.

Super simple would be to just tell people that it hits quota in the same way as the API's. And then put a task to document it with the API's that we just refer to. I don't think anything is different, and our SDK is very close to the API.

If you wanted to try to put in a bit of guidance you could:

* `data` commands don't incur any quota, with the exception of 'data asset-download' which hits quota every time you use it, and charges quota for the whole scene (I'm 90% sure on this, will check to be 100%)
* `orders` commands only incur quota on `orders create` call. Clipping is recommended as the quota will only be for the area you clip to. Composite currently counts quota for the input scenes, but will soon be fixed to just be the area output. Other tools don't consume any extra quota.
* `subscriptions` commands incur quota just as using the subscriptions API does. 

But I do really think the right place to put that information is not in the SDK/CLI docs, it's in the core API docs and we'd link to it.

**Comment by JuLeeAtPlanet** [comment]
I'm good with just a statement that says "Making calls using this Planet SDK for Python consumes quota in the same way as making calls to the core Planet APIs."

I'll file an internal ticket to add the guidance to the core APIs.

**Comment by JuLeeAtPlanet** [comment]
Resolved for this project.
