### ISSUE TITLE
@- or - convention?

### ISSUE THREAD

**Issue by kapadia** [planetlabs/planet-client-python#55]
I'd like to nail down a practice that can be used between the Python and JS client for file/std input. I've been using a few geo tools that have adopted the `-` convention for accepting from stdin. For example, clipping an image to a geojson mask is accomplished with Rasterio by:

``` shell
# from stdin
cat region.geojson | rio mask input.tif output.tif --geojson-mask -

# from file
rio mask input.tif output.tif --geojson-mask region.geojson
```

There is no option for writing inline geojson, as this quickly become verbose for a CLI command.

For the client libraries, I'd like to adopt the practices used by Rasterio, Fiona, and the USGS client for accepting from stdin or file. I do not see a compelling reason to also support inline geojson/WKT.

Currently the JS client uses the `@-` convention, straying from other geo tools. @ischneider has taken my input on this (thanks Ian!), so the Python client supports both `@-` and `-`. This creates ambiguity in the error message returned. For example, should a geojson file not exist:

``` shell
$ planet search @aoi.geojson
Error: [Errno 2] No such file or directory: 'aoi.geojson'
```

the correct error is returned, thanks to the `@` convention. However, since it also supports inline geometries,

```
$ planet search aoi.geojson
Error: BadQuery: {"message": "Query parameter validation failed", "errors": [{"field": "intersects", "message": "WKT: Unsupported geometry type"}]}
```

results in an ambiguous error message. This can be resolved by dropping inline geometries, and always assuming a string represents a filepath. A proper file existence check will raise the correct error.

It would be nice to avoid ambiguous error messages, but more importantly, I'd like to follow in the footsteps of `rio` and `fio`, as these are my everyday tools. Good documentation and examples around this can help ensure that others follow the same workflows that we establish.

/cc @tschaub @ischneider

**Comment by ischneider** [comment]
FYI, `planet search aoi.geojson` should work if the file exists - it currently is only a problem if it doesn't exist. As noted, a WKT or inline bounding box is likely to be a common use-case. Instead of the ambiguity, if the provided file doesn't exist, the client should evaluate whether the argument, `aoi.geojson` in this case is (at least) valid JSON.

I agree with the ambiguity problems but perhaps an equally useful activity would be to proliferate the use of '@' to other tools to reduce said ambiguity :wink:

**Comment by kapadia** [comment]
> I agree with the ambiguity problems but perhaps an equally useful activity would be to proliferate the use of '@' to other tools to reduce said ambiguity :wink:

That is one option, but I don't think we're in a position to be successful here.

**Comment by jreiberkyle** [comment]
V2 will use `-` to support stdin on the cli. See #286.
