### ISSUE TITLE
Handle additional rate-limit failure modes with exponential backoff.

### ISSUE THREAD

**Issue by tbarsballe** [planetlabs/planet-client-python#551]
#279 addressed handling HTTP 429 TOO_MANY_REQUESTS failures through use of retry with exponential backoff.

Use of the Data and Orders APIs have shown additional failure modes in rate-limiting situations beyond just the HTTP 429 response, that should be handled in the same way. These include timeouts and partial responses, which may occur when many (1000+) API requests are submitted all at once, and the scaling and rate-limiting mechanisms of the APIs fail to catch them all, and may manifest as the following exceptions (assuming use of the requests library):

- requests.exceptions.ChunkedEncodingError
- requests.exceptions.ReadTimeout

In addition to these failures, occasionally 4xx or 5xx responses are returned with a blank or corrupt body, such that attempting to parse the response body results in some form of decode error (e.g. `json.decoder.JSONDecodeError` when calling `response.json()`) - this appears to be another manifestation of the above failure.

I have also observed intermittent failures specifically when submitting orders, where I receive a 5xx status with the message "Problem confirming products". This failure may also be related to rate-limiting, as a resubmission of the same order always appears to succeed. I am less certain as to whether this particular failure should be handled through the same method, as there may be cases where it is actually a relevant response.

**Comment by jreiberkyle** [comment]
I am interested in how you are triggering the `requests.exceptions.ChunkedEncodingError` and the blank/corrupt body errors. I didn't see those exceptions when working with the search endpoint, so I am guessing they are coming from other endpoints. Also curious which endpoints you are seeing users hitting with 1000+ concurrent requests. search was all I could come up with, with my limited experience.

**Comment by tbarsballe** [comment]
Those errors are much less common, and basically impossible to consistently reproduce. As far as I can tell, they generally happen in the same situations as regular rate limiting exceptions, just much less frequently. The APIs I was using when I've encountered them in the past have been Data (Search), Subscriptions (List), and Orders (Create + Get). I'm not certain which of those produced them - I was sharing my rate-limiting implementation between the three, at the time.

Orders is another (relatively) common one for 1000+ requests at once, generally in instances with lots of AOIs + Clipping (since the vertex limit usually means its easiest to just go for one AOI per order) - I've seen upwards of 10k concurrent orders before in use cases like that.

**Comment by cholmes** [comment]
Closing as #640 said it closes this one.
