### ISSUE TITLE
Better CLI information on item-type options

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#572]
In v2 it's hard to know what item-type options there are without having them memorized or having to look online. Right now I'm looking at `data search-quick` and `orders create` (though that will move to `request` soon). 

There are two places this could be better:

* In the --help, we could list the potential options for item-types. At the very least the most common ones.
* If the user doesn't supply it, as the error. v1 is much better at this:

```
(cli-v1) cholmes@x9t37m3hgt Downloads % planet data search       
Usage: planet data search [OPTIONS]
Try 'planet data search --help' for help.

Error: Missing option '--item-type'. Choose from:
	Landsat8L1G,
	MOD09GA,
	MOD09GQ,
	MYD09GA,
	MYD09GQ,
	PSOrthoTile,
	PSScene,
	PSScene3Band,
	PSScene4Band,
	REOrthoTile,
	REScene,
	Sentinel1,
	Sentinel2L1C,
	SkySatCollect,
	SkySatScene,
	SkySatVideo
(cli-v1) cholmes@x9t37m3hgt Downloads % 
```

At some point the list may be too long to maintain, but we could just put the most popular ones and have a link to the online document with the full list.

**Comment by jreiberkyle** [comment]
Let's block this on #619. When we have a way to get the item-type list from the spec, this will simply be accessing that list and displaying it as a click `Choice` type.
