### ISSUE TITLE
Update Planet Python Notebooks to v2 and give feedback

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#587]
As we have the core workflows more sorted it'd be good to start to *use* them. So it's time to update the notebooks at https://github.com/planetlabs/notebooks. Should be sure to take notes of what is trickier or if there's any issues, and report them back in this repo.

**Comment by cholmes** [comment]
It'd be good to prioritize orders download, as there are customers having trouble with V1, so providing them an updated notebook and instructions on V2 would be a win.

**Comment by mkshah605** [comment]
8/4/2022 Progress Update: Going through notebooks in order, folder by folder. Currently working through analytics notebooks. You can see "real time" updates with [checkmarks on this ticket](https://hello.planet.com/jira/browse/DEVREL-611). Working through some hairy updates on the Change Detection Heatmap notebook with @tbarsballe 's help. PR for all the updates [available here](https://github.com/planetlabs/notebooks/pull/191)

**Comment by mkshah605** [comment]
8/31/2022 About 75% done with notebooks. Going mostly in order, with a few exceptions. Currently working on Orders notebooks. More detailed progress/notes on [this JIRA ticket.](https://hello.planet.com/jira/browse/DEVREL-611)

**Comment by cholmes** [comment]
Closed with https://github.com/planetlabs/notebooks/pull/191
