### ISSUE TITLE
document exception handling in docs

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#592]
We have exception handling documented in the code repo ([DESIGN.md](https://github.com/planetlabs/planet-client-python/blob/main/DESIGN.md#errors)) but not in the docs. Add this to the docs.

**Comment by JuLeeAtPlanet** [comment]
This is a duplicate issue in that it is a sub-issue of the review of the user guide Ticket https://github.com/planetlabs/planet-client-python/issues/799 So I'm closing this issue.
