### ISSUE TITLE
Using `planet orders create` by itself feels like it hangs

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#598]
If I just do `planet orders create` it seems like nothing happens. Maybe it's waiting for stdin? All the other commands seem to do something, like say that it's expecting a file. Maybe there's a good reason it's not doing it, but as a user I'm not sure what I'm supposed to try next, while the others tend to flag what it's expecting next, and point people towards using the command with `--help`

**Comment by jreiberkyle** [comment]
Being new to piping myself, I was also surprised by this behavior. I can say that it is the same behavior one gets if they call `tee` or `grep a` (here, 'a' can be replaced by any pattern) without a pipe in, they just wait for user input.

**Comment by jreiberkyle** [comment]
yeah, the UI of less does seem more friendly. I agree with spending time to see if we can implement that approach in the SDK CLI.

**Comment by cholmes** [comment]
Moving to beta.2, as #835 should solve this.

**Comment by jreiberkyle** [comment]
fixed with #840
