### ISSUE TITLE
Allow item types specified to be case insensitive

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#599]
When ordering or searching I don't always remember if it's `SkySatCollect` or `SkysatCollect`. 

I don't feel like we're ever going to make some item types that have the same name but different cases, so seems like it'd be nice for users to just get the case right for them - let them enter case-insensitive.

It looks like the API does require the right case sensitivity, but I'm starting to lean towards with the CLI in particular we should be making things easier for the user instead of just trying to stick exactly to what the API's do.

**Comment by jreiberkyle** [comment]
Absolutely let's make this case-insensitive. This is an effort that requires validation against the OpenAPI spec. #619 is a related ticket and speaks to the deeper work. I will look at reworking that ticket to include this ticket and #636 .

**Comment by cholmes** [comment]
Note this occurs on `planet data search` - `planet orders request` handles it properly. Should check any other place we use item types though.

**Comment by kevinlacaille** [comment]
Would love to throw a `case_sensitive=False` in the `type=types.CommaSeparatedString()` call, however `types.CommaSeparatedString()` takes no arguments. However, maybe we can deal with it in the `check_item_types()` callback function? TBD

**Comment by jreiberkyle** [comment]
@kevinlacaille looks like you took this ticket back in Sept. My guess is that it is currently backlogged? Could you throw up a status and relinquish the ticket?

**Comment by kevinlacaille** [comment]
Hey @jreiberkyle and @cholmes, thanks for reminding me to close this! I believe one of my PRs in October 2022, #713, solved this issue. 

A quick run of `pytest -k test_data_search_cmd_filter_success` and changing its pytest parameters (i.e., SkySatScene -> skysatscene) confirms that `planet data search` is now case insensitive. 

```shell
❯ pytest -k test_data_search_cmd_filter_success
================================= test session starts ==================================
platform darwin -- Python 3.9.6, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/kevin.lacaille/code/repos/planet/planet-client-python/tests, configfile: pytest.ini
plugins: asyncio-0.16.0, respx-0.19.0, anyio-3.3.0, cov-4.0.0
collected 430 items / 427 deselected / 3 selected

integration/test_data_cli.py::test_data_search_cmd_filter_success[PSScene] PASSED [ 33%]
integration/test_data_cli.py::test_data_search_cmd_filter_success[skysatscene] PASSED [ 66%]
integration/test_data_cli.py::test_data_search_cmd_filter_success[PSScene, skysatscene] PASSED [100%]

========================== 3 passed, 427 deselected in 0.27s ===========================
```

**Comment by cholmes** [comment]
Hrm, I'm not seeing this on beta1:

```
(planet-v2-cli) (base) cholmes@X9T37M3HGT Downloads % planet --version
planet, version 2.0.0-beta.1
(planet-v2-cli) (base) cholmes@X9T37M3HGT Downloads % planet data filter | planet data search SkysatCollect
Error: {"general": [], "field": {"item_types": [{"message": "Not all item types requested exist or are accessible"}]}}
```
I can try dev branch, but your comments above seem to indicate that it should be there in beta.1

**Comment by kevinlacaille** [comment]
Ah, I must be missing something somewhere. On my version, `2.0.0-beta.2dev`, this gives the same error. Re-opening and will get to this next.

**Comment by kevinlacaille** [comment]
Oh boy! We've got a working solution 👍
