### ISSUE TITLE
Document way to get a count of a search you are about to do.

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#615]
It's often nice to just see how many results a search will return, instead of running the full results. 

In v1 `planet data search download --dry-run` would provide this. Not sure exactly how.

I will note it's likely possible to do this with `planet data stats` - but we should at least have an example / docs on how to get the call with just the total count (like not in buckets, just totaling up). Probably can just do some cli magic for it.

**Comment by jreiberkyle** [comment]
cli magic:
```planet data search --limit 0 --filter filter.json PSScene | wc -l```

changing this to a doc ticket.

**Comment by cholmes** [comment]
> `planet data search --limit 0 --filter filter.json PSScene | wc -l`

That's going to be a really heavy call for things like 'PSScene all time collects', which is one of the common things that I do. Like it'd take hours if not days. I was thinking more `planet data stats` and then use `jq` to extract the count for each year and then add up all the counts.

**Comment by cholmes** [comment]
Figured this out: `jq '.buckets | map(.count) | add'`!

It's included in #891 PR.

**Comment by JuLeeAtPlanet** [comment]
As noted above: included in https://github.com/planetlabs/planet-client-python/pull/891 PR.
