### ISSUE TITLE
planet order request: be more helpful on what bundles are available for a given item_type

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#618]
Right now `planet order request` fails if item_type and bundle are incompatible by saying what item-types are compatible with the specified bundle. It would be more helpful to switch this so that it indicates what bundles are compatible with an item-type.

This has been hitting me as I've changed over from `PSScene4Band` to `PSScene` item-type, which is not compatible with the `analytic` bundle.

**Comment by kevinlacaille** [comment]
Is anyone still having this issue? I just tried requesting a pansharpened item type for a visual bundle and it gave me an error message telling me which item types are valid. See below:

```
❯ planet orders request \
--name Bangladesh_2018_visual_mosaic \
--id 20180418_043113_1053,20180418_043112_1053 \
--item-type pansharpened \ 
--bundle visual
Usage: planet orders request [OPTIONS]
Try 'planet orders request --help' for help.

Error: Invalid value: item_type - 'pansharpened' is not one of 'Landsat8L1G', 'PSOrthoTile', 'PSScene3Band', 'PSScene', 'REOrthoTile', 'Sentinel2L1C', 'SkySatCollect', 'SkySatScene'.
```

**Comment by kevinlacaille** [comment]
Ah I understand now, I had it backwards in my head the whole time.

On it!
