### ISSUE TITLE
Support filtering by 'area coverage' in data API requests

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#632]
One of the clearest pieces of feedback so far is that it'd be amazing if the CLI could support the same 'area coverage' type of filtering that Planet explorer enables. 

The core idea is that for a geometry you're filtering on you'd like to specify a percent of that geometry covered. Explorer does it based on 'day', aggregating all strips for the day. 

This isn't an operation supported by the data API, and indeed it would likely be quite complicated to do fully server side. Explorer does it by building up a bitmask on the client side, aggregating by day. We could likely do something similar, and there are ideas like using Planet's numpy tiles directly.

**Comment by asonnenschein** [comment]
Closing as won't do, this feature should be implemented in the API.
