### ISSUE TITLE
Installation failure Windows 11

### ISSUE THREAD

**Issue by Deadpeng** [planetlabs/planet-client-python#635]
![planet issue](https://user-images.githubusercontent.com/108851002/177686696-3eb1f85e-9225-4755-8b26-7b475f42846a.png)

Hello staff at Planet,

I tried pip installing Planet on Windows CMD. While the installation was successful, I could not open up Planet nor get to the API afterwards. Please kindly assist.

**Comment by asonnenschein** [comment]
Closing as resolved per @cholmes' comment, this is a windows path issue and can be resolved with the linked StackOverflow ticket.
