### ISSUE TITLE
Planet SDK v2-Orders v2: Error message is not proper for invalid bundle for valid item type

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#660]
**Environment**: planet, version 2.0a1

**Test steps**:
1. create an order with invalid bundle for PSScene item type.

`planet orders request --name "rajapsscene" --item-type PSScene --bundle analytic --id 20220712_183242_24_2478,20220712_183239_96_2478` 
**Expected**: It should display as invalid bundle for the item type

**Actual:** It is displaying error as PSScene is not valid item type & PSScene is not displayed as item type

`Error: Invalid value: item_type - 'PSScene' is not one of 'Landsat8L1G', 'PSOrthoTile', 'PSScene3Band', 'PSScene4Band', 'REOrthoTile', 'Sentinel1', 'Sentinel2L1C', 'SkySatScene', 'SkySatCollect'.`
**Additional Info**:
When valid bundle is provide to command it is working fine for the PSScene
`planet orders request --name "rajapsscene" --item-type PSScene --bundle visual --id 20220712_183242_24_2478,20220712_183239_96_2478`

When we provide the command with PSOrtho , then it is displaying the PSScene in the error message

`planet orders request --name "rajaclip" --item-type PSOrtho --bundle visual --id 20220712_183242_24_2478,20220712_183239_96_2478`
```
Usage: planet orders request [OPTIONS]
Try 'planet orders request --help' for help.
Error: Invalid value: item_type - 'PSOrtho' is not one of 'Landsat8L1G', 'PSOrthoTile', 'PSScene3Band', 'PSScene', 'REOrthoTile', 'Sentinel2L1C', 'SkySatCollect', 'SkySatScene'.
```

**Comment by jreiberkyle** [comment]
this now works as expected (note the flag `--id` has been removed):

```bash
$> planet orders request --name "rajapsscene" --item-type PSScene --bundle analytic 20220712_183242_24_2478,20220712_183239_96_2478
Usage: planet orders request [OPTIONS] IDS
Try 'planet orders request --help' for help.

Error: Invalid value: bundle - 'analytic' is not one of 'analytic_udm2', 'analytic_3b_udm2', 'analytic_8b_udm2', 'visual', 'basic_analytic_udm2', 'basic_analytic_8b_udm2', 'analytic_sr_udm2', 'analytic_8b_sr_udm2'.
```
