### ISSUE TITLE
Planet Cli SDK v2: Data-API: search-create with pipe command is not working for data-api

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#662]
**Environment**: planet cli SDK, version 2.0a1

**Test steps**:
1. create a search-create command with pipe command as below

`planet data filter --range clear_percent gt 98 --date-range acquired gte 2021-07-01 --date-range acquired lt 2021-08-01 | planet data search-create test PSScene`
`Expected`: It should create a saved search with search id

**Actual**: It is not creating a saved search & displaying error

```
Usage: planet data search-create [OPTIONS] NAME ITEM_TYPES FILTER
Try 'planet data search-create --help' for help.

Error: Missing argument 'FILTER'.
```

**Comment by jreiberkyle** [comment]
To use stdin for filter, use the `-` identifier, e.g. 
```bash
planet data filter --range clear_percent gt 98 --date-range acquired gte 2021-07-01 --date-range acquired lt 2021-08-01 | planet data search-create test PSScene - 
```
