### ISSUE TITLE
Planet SDK v2 - Orders v2: Unable to create an order using an order id and override the item IDs with like opiton

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#666]
**Environment**: planet, version 2.0a1

**Test steps**:
1. create an order then override with different item ids with below command

`planet orders get 5558e765-ab4f-4512-9ea6-db6c459a7014 >planet orders request --like --id 20220725_183517_22_2489,20220725_183514_95_2489`

**Expected**: It should create an order successfully

**Actual**: It is displaying error as below
`bash: planet: Is a directory--error`

Also for the below command, error is displayed
planet orders get 5f80c095-8c7c-48ff-86d8-50ee155a3635 > planet orders request --like --name IAmACopy

**Comment by cholmes** [comment]
Thanks for the report @rajashekarmamidala!  I'm guessing you got the `--like` command from https://github.com/planetlabs/planet-client-python/blob/main/design-docs/CLI-Orders.md#request? 

That document is what we're planning to do, but does represent the state of what's implemented. The definitive list of what's actually implemented is the docs, see https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/

Would the `--like` option be useful to you? We'll be working soon to figure out what to prioritize. Thanks!
