### ISSUE TITLE
Trying to download an order using order ID and failing due to a 302

### ISSUE THREAD

**Issue by olepinard** [planetlabs/planet-client-python#678]
I am trying to loop through order ID's and am erroring out with the error included below. 

`   async with Session() as sess:
        client = OrdersClient(sess)
        for order in order_ids:
            print(order)
            await client.download_order(order)
`
Is it possible that the 302 is not being handled correctly?

[302_error_output.txt](https://github.com/planetlabs/planet-client-python/files/9376717/302_error_output.txt)

**Comment by cholmes** [comment]
Hey @olepinard - super sorry for the slow response, this slipped through the cracks with vacation, etc. Will try to investigate this soon - thanks for reporting it!

**Comment by sgillies** [comment]
This will be fixed in 2.0a3.

**Comment by cholmes** [comment]
Closing this as #685 merged and a3 was released. @olepinard - feel free to re-open if the new release doesn't handle your issue.
