### ISSUE TITLE
Planet Cli2 SDK--Data-API: Some of the commands are not working in Data-API

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#686]
**Environment**: planet, version 2.0a2

Some of the commands in Data-API are not working

search-update, search-delete, search-list, search-run
item-get, asset-activate, asset-wait, asset-download

When the commands are executed it is displaying 

```
planet data search-delete e9898ccd1ad6498d8fd74f0319bb8e7a
Usage: planet data [OPTIONS] COMMAND [ARGS]...
Try 'planet data --help' for help.

Error: No such command 'search-delete'.
```

When I tried the **planet data --help** , it is displaying only below are available
```
Usage: planet data [OPTIONS] COMMAND [ARGS]...

  Commands for interacting with the Data API

Options:
  -u, --base-url TEXT  Assign custom base Orders API URL.
  --help               Show this message and exit.

Commands:
  filter         Create a structured item search filter.
  search         Execute a structured item search.
  search-create  Create a new saved structured item search.
  search-get     Get a saved search.
  stats          Get a bucketed histogram of items matching the filter.

```

**Comment by cholmes** [comment]
Hey @rajashekarmamidala - thanks for the report. Similar to #666 those commands are designed, but not yet implemented. We made the decision to prioritize the main search and download flow with orders and just quick search, so deprioritized the above commands. Do you have a use case for them? If so would love to hear it, and we can definitely try to prioritize the functionality.

**Comment by cholmes** [comment]
Closing this in favor of the individual tracking issues we have for these, like #500 #497 #505 #507 #506 #504 #503 #502 #501
