### ISSUE TITLE
Planet Cli2 SDK--Subscriptions: Error message is displayed as Null when subscription is cancelled

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#688]
Environment : planet, version 2.0a3.dev0

Test steps:
1. Create a subscription as below
`C:\planet_cli2\planet-client-python>planet subscriptions create sub_create.json`

`{"name": "QE Simple-new format-Skysatscene-PCLi", "source": {"type": "catalog", "parameters": {"asset_types": ["ortho_analytic"], "item_types": ["SkySatScene"], "geometry": {"coordinates": [[[-122.78320312499999, 37.56199695314352], [-121.95373535156249, 37.56199695314352], [-121.95373535156249, 38.16911413556086], [-122.78320312499999, 38.16911413556086], [-122.78320312499999, 37.56199695314352]]], "type": "Polygon"}, "start_time": "2022-09-07T15:40:05Z", "end_time": "2022-09-30T23:55:55Z"}}, "delivery": {"type": "google_cloud_storage", "parameters": {"bucket": "subscriptions_qe", "credentials": "<REDACTED>"}}, "created": "2022-09-07T15:37:37.90029Z", "_links": {"_self": "https://api.planet.com/subscriptions/v1/77a759c1-df1f-4e20-93b9-300af0fd9a2a"}, "status": "preparing", "id": "77a759c1-df1f-4e20-93b9-300af0fd9a2a", "updated": "2022-09-07T15:37:37.90029Z"}`

2. Now try to Cancel the subscription with ID which is created above

`planet subscriptions cancel 77a759c1-df1f-4e20-93b9-300af0fd9a2a`

Expected : It should display as the subscription is Cancelled

Actual: It displaying as "null" when the command is executed

```
C:\planet_cli2\planet-client-python>planet subscriptions cancel 77a759c1-df1f-4e20-93b9-300af0fd9a2a
null
```

**Comment by jreiberkyle** [comment]
null printout removed in #830
