### ISSUE TITLE
Planet Cli2 SDK - Orders V2: Stac metadata is applied by default when an order is placed

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#696]
**Environment**: planet, version 2.0a3.dev0

**Test Steps**
1. Create an order as below
`planet orders request --name "test order-psscene" --id 20210315_005834_36_2259 --bundle visual --item-type PSScene`

**Expected**: It should not have the Stac metadata 

**Actual**: Stac metadata is displayed by default
`{"name": "test order-psscene", "products": [{"item_ids": ["20210315_005834_36_2259"], "item_type": "PSScene", "product_bundle": "visual"}], "metadata": {"stac": {}}}`

**Additional Info**:
When an order is placed thru API the Stac metadata is not added by default

**Comment by kevinlacaille** [comment]
This issue has been addressed by PR #697 👍
