### ISSUE TITLE
Filter produces no output

### ISSUE THREAD

**Issue by bosth** [planetlabs/planet-client-python#703]
`planet data filter --std-quality False --permission False` produces nothing on stdout

Both of the following work as expected:
* `planet data filter --std-quality False` 
* `planet data filter --permission False`

Version: 2.0a3

**Comment by cholmes** [comment]
I think this should be fixed in the next release with https://github.com/planetlabs/planet-client-python/pull/654  Was done awhile ago, but just didn't get it merged. @bosth - it should be merged on main if you want to try it out there. Or we're hoping to get a new release out pretty soon.

**Comment by cholmes** [comment]
I believe this should be fixed in a4 release.
