### ISSUE TITLE
Possible to create a filter with conflicting rules

### ISSUE THREAD

**Issue by bosth** [planetlabs/planet-client-python#704]
`planet data filter --permission False --string-in quality_category test` produces the following filter:

`{"type": "AndFilter", "config": [{"type": "StringInFilter", "field_name": "quality_category", "config": ["test"]}, {"type": "StringInFilter", "field_name": "quality_category", "config": ["standard"]}]}`

I think it would be nice if we weren't setting filters by default (i.e. quality of `standard`) anyway, but this issue is another reason to reconsider.

**Comment by jreiberkyle** [comment]
We went with not setting filters by default, see #842. That resolves this issue.
