### ISSUE TITLE
`orders download` doesn't seem to work any more.

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#708]
Using 2.0a3 I get an error when trying to download an order:

```
% planet orders download f4bc1ea3-02f7-409e-b451-23554bfa85a9         
Error: 
```

I tried to turn on a debug `--verbosity`, but it didn't seem to work for this command, so the above is all I've got.

I installed 2.0a1 on a clean environment and the same order worked just fine. 

At least one customer has also reported this problem.

**Comment by kevinlacaille** [comment]
I am getting a similar error with the same version:

```
% planet orders download 7513d6ff-64ca-4042-810d-684b63931ca7
Error: {"message":"Could not load order ID: 7513d6ff-64ca-4042-810d-684b63931ca7."}
```

**Comment by jreiberkyle** [comment]
@kevinlacaille two questions:
1 - is the api key at PL_API_KEY the right auth info? Because that's not the one that is set with `planet auth init`
2 - did you create this order? when? curious if the order is still active. maybe try again with the whole order creation sequence and include the sequence used here?

**Comment by kevinlacaille** [comment]
@jreiberkyle I did not create this order and I realize that this is the issue. The customer who I was helping who owns this order was having an issue with downloading it, has now resolved their issue, which seems to be independent of the SDK. 

Although "`Could not load order ID`" isn't a bad error message, I wonder if we could provide the user with a more helpful error message.

**Comment by cholmes** [comment]
Closing this, as looks like this was basically the same as #678  and I didn't realize I was on 2.0a2. Upgrade to 2.0a3 fixed it - apologies for the noise.

**Comment by jreiberkyle** [comment]
@cholmes doesn't look like this got closed so I'm pushing the button. feel free to reopen if needed

**Comment by cholmes** [comment]
Whoops, clicked the wrong button. Thanks!
