### ISSUE TITLE
consider removing request-1.json from root folder

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#731]
https://github.com/planetlabs/planet-client-python/blob/main/request-1.json showed up in the root folder with the merge of #718 - can we remove this?

**Comment by cholmes** [comment]
Ah shoot, sorry about that. Feel free to remove it, or I can do it
hopefully later today or Monday when I’m on my computer.

**Comment by jreiberkyle** [comment]
looks like this got fixed at some point.
