### ISSUE TITLE
Potentially incorrect return type of wait_asset in data client

### ISSUE THREAD

**Issue by jamred** [planetlabs/planet-client-python#733]
wait_asset's [return type hint](https://github.com/planetlabs/planet-client-python/blob/bc29caafd570c883b5b67072bcf226563dbf3460/planet/clients/data.py#L572) say it returns a string, but I believe it's [actually returning a dict](https://github.com/planetlabs/planet-client-python/blob/bc29caafd570c883b5b67072bcf226563dbf3460/planet/clients/data.py#L627). 

Assuming I'm not crazy and this is should be a dict, and that this wasn't found earlier, I'm surprised that it passed mypy. You may want to make sure it's running correctly.

**Comment by jreiberkyle** [comment]
Yeah, it looks like you're right. It's an easy fix, but I'm also surprised our tests didn't catch it so we'll look into it.

**Comment by jreiberkyle** [comment]
this was picked up by the latest mypy tests and is fixed in #744
