### ISSUE TITLE
Planet SDK Cli2: Unable to set the base url with planet auth command

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#748]
Environment : planet, version 2.0a6dev 

Test steps:
1. Try to set up the base-url using the auth value as below

planet auth --base-url https://ordersv2.next.prod.planet-labs.com  init --email validemail --password validpassword

planet auth -u https://ordersv2.next.prod.planet-labs.com  init  --email validemail --password validpassword

**Expected**: It should set the --base-url/-u properly without any error
**Actual**: It is displaying error 

Some times it is displaying as  Error: Incorrect email or password.
however if we remove the -u & --base-url then no error is displayed

**Additional info**:
If the base-url is given as api.planet.com then it says not found

```
planet auth --base-url https://api.planet.com  init --email <valid-email>--password <valid-password>
Error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by rajashekarmamidala** [comment]
[base-url-error.txt](https://github.com/planetlabs/planet-client-python/files/9973315/base-url-error.txt)
error log file when the above command is executed

**Comment by tbarsballe** [comment]
orders.next auth is likely to change in the future, so we won't be addressing this right now.
