### ISSUE TITLE
document environment variables and how they affect behavior

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#749]
We have no documentation on environment variables in the SDK and how they affect behavior.

Right now, the only environment variable is `PL_API_KEY`. The CLI and Python API both default to using this environment variable before checking the stored auth information. This environment variable should be documented on its own, with information about how to set it, how to unset it, and how it affects behavior, and it should be mentioned in all discussions around auth.

**Comment by cholmes** [comment]
This is documented in https://planet-sdk-for-python-v2.readthedocs.io/en/latest/get-started/quick-start-guide/#your-api-key-as-an-environment-variable It's not quite all you were tasking for, but I think we're also moving away from the CLI being able to set / use this. So going to close this.
