### ISSUE TITLE
Update language to introduce CLI in a more positive way

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#750]
"It’s not too tricky, but it does require a presence of mind to complete."

In https://github.com/planetlabs/planet-client-python/blob/90180db83656e96b32751017ac03ec4fa91f842a/docs/get-started/quick-start-guide.md#step-1-install-python-37-and-a-virtual-environment

The tone of this strikes me as dismissive and potentially judgemental of someone who may find this difficult.

In general, this line seems to talk about CLI installation as a "long walk in the desert" somehow. I would recommend a way of introducing CLI installation in a positive way. I mean, the user has to install any CLI they use. They are used to that, this is a part of opt-in technology. pip is just how they install it. I'm biased, but it doesn't seem like the level of effort is necessarily onerous nor does it need to be communicated as such.

_Originally posted by @jreiberkyle in https://github.com/planetlabs/planet-client-python/pull/747#discussion_r1018252245_
      
Adding a similar language issue from that PR here, about the fourth paragraph in https://github.com/planetlabs/planet-client-python/blob/f1519ecc5695ffb6824c1194f1a9d43f69c4d82e/docs/get-started/venv-tutorial.md

        I wouldn't presume to know the user's experience here. And suggesting it is awkward may subconsciously push them into feeling it IS awkward, where they were pretty fine with it before the suggestion. I like the positive spin: tell them why it is helpful and tell them how it can be done the simplist way possible. And maybe give them a ref to find out more.

_Originally posted by @jreiberkyle in https://github.com/planetlabs/planet-client-python/pull/747#discussion_r1018266146_

**Comment by tbarsballe** [comment]
Fixed by https://github.com/planetlabs/planet-client-python/commit/1faf2bf1b37212eed428453b8642e14a0d894bcc
The venv-tutorial is less a part of the primary docs, and less of an issue, so we're leaving that as-is
