### ISSUE TITLE
better documentation of how to use Session

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#760]
The Session class implements rate limiting which allows for smooth asynchronous communication with Planet servers. However, this rate-limiting only works with *one* Session being used. Multiple Sessions will bypass rate-limiting. This is a very important concept for properly using Session but it isn't in our docs and in fact we even forget how to use it properly (see #759, which I totally missed on my PR review of the example).

Let's clearly document (and highlight) proper usage of Session (demonstrated in [orders_create_and_download_multiple_orders.py](https://github.com/planetlabs/planet-client-python/blob/main/examples/orders_create_and_download_multiple_orders.py))

**Comment by cholmes** [comment]
Would it be reasonable to mostly just link from the docs to the example @jreiberkyle ? Or you also want us to spell out a specific section on rate limiting and advising not to use multiple sessions?

**Comment by JuLeeAtPlanet** [comment]
Draft provided to @jreiberkyle in off-channel comms.

**Comment by JuLeeAtPlanet** [comment]
This is a duplicate issue in that it is a sub-issue of the review of the user guide Ticket #799 So I'm closing this issue.
