### ISSUE TITLE
Docs on APIs implemented are inconsistent

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#761]
**Expected behavior**
The docs should say:
Orders
Data (mostly complete)
Subscriptions (in progress)

Then either mention or don't mention all of the other APIs that aren't implemented. Maybe only mention the APIs we plan to implement. 

**Actual behavior (describe the problem)**
The docs on [readthedocs](https://planet-sdk-for-python-v2.readthedocs.io/en/latest/), in our [README](https://github.com/planetlabs/planet-client-python#quick-start), and on the [quick start guide](https://github.com/planetlabs/planet-client-python/blob/main/docs/get-started/quick-start-guide.md) are all inconsistent about what is and isn’t implemented.

**Comment by cholmes** [comment]
I think this is fixed, with #765 and new docs.
