### ISSUE TITLE
Not possible to get all results of a search

### ISSUE THREAD

**Issue by bosth** [planetlabs/planet-client-python#77]
The `--limit` parameter doesn't allow the user to set the maximum number of search results to be *unlimited*. It might be useful to allow the user to override all limits on the number of results since this is possible with the Python client by setting the limit to `None`.

**Comment by ischneider** [comment]
There is an inherent danger here - a search (today) with no filters or limit would yield 2463252 results

**Comment by bosth** [comment]
Yeah ... but the client and API are just as dangerous.

**Comment by ischneider** [comment]
Not totally as the number of results is limited per page and the CLI seamlessly traverses pages

**Comment by bosth** [comment]
Good point.
