### ISSUE TITLE
Add Sentinel-2 to Harmonization tool

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#772]
**Is your feature request related to a problem? Please describe.**
Our SDK only allows data harmonization with Dove Classic, however the [openAPI spec ](https://developers.planet.com/apis/orders/reference/#tag/Orders/operation/createOrder) has added Sentinel-2 as a target sensor for harmonization.

I propose we add Sentinel-2 as an option for harmonization to the Orders API.

**Describe the solution you'd like**

Current [harmonization tool](https://github.com/planetlabs/planet-client-python/blob/main/planet/order_request.py#L432):
```
def harmonize_tool() -> dict:
    '''Create the API spec representation of a harmonize tool.

    Currently, only "PS2" (Dove Classic) is supported as a target sensor, and
    it will transform only items captured by “PS2.SD” (Dove-R).
    '''
    return _tool('harmonize', {'target_sensor': 'PS2'})
```

Proposed solution:
```
def harmonize_tool(target_sensor: str) -> dict:
    '''Create the API spec representation of a harmonize tool.

    Currently, only "PS2" (Dove Classic) and "Sentinel-2" are supported as 
    target sensors. Dove-R can only be transformed by PS2 and Sentinel-2 can 
    only transform surface reflectance bundles for PSScene 
    (ie., analytic_8b_sr_udm2, analytic_sr_udm2).
    '''
    return _tool('harmonize', {'target_sensor': target_sensor})
```

I also suggest adding a test for hamonization in `tests/unit/test_order_request.py`:
```
@pytest.mark.parametrize("target_sensor", ["PS2", "Sentinel-2"])
def test_harmonization_tool(target_sensor):
    ht = order_request.harmonize_tool(target_sensor)
    expected = {'harmonize': {'target_sensor': target_sensor}}
    assert ht == expected
```

**Additional context**
I would double check the sensor harmonization compatibility on the [Dev Center](https://developers.planet.com/apis/orders/tools/#harmonization).

**Comment by cholmes** [comment]
Added to b1 milestone. Consider this 'nice to have', not a blocker for release - if the key tickets land we can move it. 

Your proposal looks good, but I'd adopt the language in the dev center more directly - the 'transformed by' / 'transform' language isn't super clear.

```
Currently, only "PS2" (Dove Classic) and "Sentinel-2" are supported as 
    target sensors. The Sentinel-2 target only harmonizes PSScene 
    surface reflectance bundle types (analytic_8b_sr_udm2, analytic_sr_udm2). 
    The PS2 target only works on analytic bundles
     from Dove-R (PS2.SD).
```
