### ISSUE TITLE
`planet subscriptions results` not returning more than 20 results

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#777]
**Expected behavior**
`planet subscriptions results <sub-id>` to return 100 results as specified as the default in the documentation. Or to return 
the proper number of results if `--limit` is greater than 20 (it works properly if the limit is less than 20)

**Actual behavior (describe the problem)**

Only 20 results are returned, even if the `--limit` is set to be greater than 20. 

It seems like the cli client is not actually paging through results - it just does the first 20 and stops. I verified that the http endpoint has more results. It has 20 on the first page, but it has a 'next' link that has 20 per page.

**Workaround**
Going to the http end point directly and following the 'next' links?

**Minimum, Complete, Viable Code Sample**

```console
> planet subscriptions results <sub-id> --limit 21
```

Should result in 21 calls returned, only 20 are.

**Environment Information**
* Operation System Information: macOS-12.2.1-arm64-arm-64bit
* Python version 3.9.15: (main, Oct 11 2022, 21:39:54)  [Clang 14.0.0 (clang-1400.0.29.102)]
* Planet package version: planet, version 2.0a7dev

**Installation Method**
* pip

**Comment by jreiberkyle** [comment]
I'm going to look into this a little as I work on #706 - my first guess is that the issue is related to the underlying pager and it's curious that subscriptions would have an issue orders and data don't exhibit. Could you provide a subscription request I can use to quickly create 22 subscriptions?

**Comment by cholmes** [comment]
Will do.

**Comment by jreiberkyle** [comment]
Hmm.. I am unable to replicate. I submitted a ton of subscriptions then did the following tests:
```console
planet-client-python$> planet subscriptions list --limit 20 | wc
      20    1880   31792
planet-client-python$> planet subscriptions list --limit 25 | wc
      25    2350   39740
```

**Comment by jreiberkyle** [comment]
doesn't look like the SDK is imposing any filters, here's the log entry showing the request that was sent:
```2022-11-17 11:24:07,053 - planet.http - INFO - GET https://api.planet.com/subscriptions/v1? - Sent``

**Comment by cholmes** [comment]
`list` is fine - `planet subscriptions results` is the issue.

**Comment by jreiberkyle** [comment]
ok I figured this out. the issue is that the code for paging through results followed the openAPI spec for the key for the entry for the next page, which is specified as `_next`. When I looked at the response I saw the key is actually `next`. So this is a two-parter. We can fix the SDK to use `next` which results in the expected behavior. But we also need to have the openapi spec updated. Actually, when I look at the openapi spec, it looks like the entirely wrong response is documented - it doesn't have an entry for 'results' as one would expect:

https://developers.planet.com/docs/subscriptions/reference/#tag/results/operation/getResults

**Comment by jreiberkyle** [comment]
Here's the line that needs to be changed. https://github.com/planetlabs/planet-client-python/blob/ccc2953528b741c91c6fa7b51e1745f9ed5ab934/planet/clients/subscriptions.py#L224

**Comment by jreiberkyle** [comment]
here's what the response schema should look like - this is for [subscriptions](https://developers.planet.com/docs/subscriptions/reference/#tag/subscriptions/operation/listSubscriptions):
![image](https://user-images.githubusercontent.com/2984664/202563070-4998814b-799c-4e01-a734-fe19f12f2a9b.png)
You'd want to replace 'subscriptions' with 'results' here.
