### ISSUE TITLE
Create beta version of SDK documentation

### ISSUE THREAD

**Issue by JuLeeAtPlanet** [planetlabs/planet-client-python#783]
**Is your feature request related to a problem? Please describe.**

[Python SDK documentation](https://planet-sdk-for-python-v2.readthedocs.io/en/latest/python/sdk-guide/) is in draft note forms, having be extracted and moved around as part of re-org.

**Describe the solution you'd like**

It's time to create a beta version of this content

**Describe alternatives you've considered**

n/a

**Additional context**

Required by PM as part of Beta release

**Comment by cholmes** [comment]
Up now at https://planet-sdk-for-python-v2.readthedocs.io/en/latest/
