### ISSUE TITLE
Planet Cli2 SDK: Orders v2: Unable to create orders with harmonize tool

### ISSUE THREAD

**Issue by rajashekarmamidala** [planetlabs/planet-client-python#787]
Planet version: planet, version 2.0a7dev

[harmonize error.txt](https://github.com/planetlabs/planet-client-python/files/10067907/harmonize.error.txt)

**Test steps**
1. create an order with harmonize tool with PSOrthoTile item type as below
2.  planet orders request PSOrthoTile analytic  --name "test harmonize" --id 5321806_3445528_2022-01-25_1012 --tools D:\cli2files\harmonize.json > testharmonize.json

{"name": "test harmonize", "products": [{"item_ids": ["5321806_3445528_2022-01-25_1012"], "item_type": "PSOrthoTile", "product_bundle": "analytic"}], "tools": [{"harmonize": {"target_sensor": "PS2"}}], "metadata": {"stac": {}}}

Harmonize file : [   {      "harmonize": {        "target_sensor": "PS2"      }    }]

3. planet orders create  testharmonize.json

**Expected behavior**
Order should be created successfully with harmonize tool 

**Actual behavior (describe the problem)**
Unable to create orders with harmonize tool. Error is displayed while execution

**Comment by jreiberkyle** [comment]
Thank you for this report! Can you provide the traceback of the error that
is displayed?

**Comment by rajashekarmamidala** [comment]
I have already attached to the bug with harmonize error. txt file

**Comment by cholmes** [comment]
Can you try this again? I tried to replicate and it worked fine for me. And your error logs seem to be some sort of connection issue.

**Comment by rajashekarmamidala** [comment]
I tried today &  working fine.
Order ID
{"_links": {"_self": "https://api.planet.com/compute/ops/orders/v2/dd287125-b17d-4a1e-9607-5e1902e431e4"}, "created_on": "2022-11-30T05:48:05.374Z", "error_hints": [], "id": "dd287125-b17d-4a1e-9607-5e1902e431e4", "last_message": "Preparing order", "last_modified": "2022-11-30T05:48:05.374Z", "metadata": {"stac": {}}, "name": "testharmonize-psorthotile", "products": [{"item_ids": ["5321806_3445528_2022-01-25_1012"], "item_type": "PSOrthoTile", "product_bundle": "analytic"}], "state": "queued", "tools": [{"harmonize": {"target_sensor": "PS2"}}]}
