### ISSUE TITLE
Allow mosaic search based on AOI

### ISSUE THREAD

**Issue by bosth** [planetlabs/planet-client-python#79]
The `mosaic-quads` command should support AOI intersection like `planet search` does since the API also supports this: https://www.planet.com/docs/v0/mosaics/#get-mosaic-quads.

**Comment by ischneider** [comment]
Relatively low priority as mosaics are typically global extent and mostly limited access.

**Comment by bosth** [comment]
This has been added, but only works for GeoJSON.

**Comment by sarasafavi** [comment]
fixed for v1 API with #140
