### ISSUE TITLE
Validate target_sensor with a global set of target sensors

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#793]
**Is your feature request related to a problem? Please describe.**
Related to PR #780 / https://github.com/planetlabs/planet-client-python/pull/780#discussion_r1026822104

Validate the `target_sensor` input in `planet.order_request()` by checking if the value is found within a global set, say something like `VALID_TARGET_SENSORS`, that enumerates the option.

**Describe the solution you'd like**
Add the global, `VALID_TARGET_SENSORS`, which would contain all of the valid target sensors, in `planet.specs`.

In `planet.specs` around line 35:
```
VALID_TARGET_SENSORS = ["PS2", "Sentinel-2"]
```

In the `tests.unit.test_order_request.test_harmonization_tool()`
```
from planet.specs import VALID_TARGET_SENSORS
...
@pytest.mark.parametrize("target_sensor", VALID_TARGET_SENSORS)
<insert existing test here>
```

**Additional context**
_An aside here_: I want to point out that I'm pretty sure case-sensitivity doesn't matter as the target sensors get validated through `planet.specs.get_match()`, which is case-insensitive.

**Comment by kevinlacaille** [comment]
Perhaps do something similar to what's done for the clip tool

```python
    valid_target_sensors = ['PS2', 'Sentinel-2']

    if target_sensor.lower() not in [v.lower() for v in valid_target_sensors]:
        raise ClientError(
            f'Invalid target sensor: {target_sensor} is not in {valid_target_sensors}.')
    return _tool('harmonize', {'target_sensor': target_sensor})
```

**Comment by jreiberkyle** [comment]
whoa I was unaware of this ticket but it's pretty much what I've done in #855 . Great minds think alike!

**Comment by kevinlacaille** [comment]
Ah yes, love this - thanks for doing this!
