### ISSUE TITLE
Command name consistency

### ISSUE THREAD

**Issue by bosth** [planetlabs/planet-client-python#80]
To list all mosaics, use `mosaics` and to get details about one, use `mosaic`.

To list all worksapces, use `list-workspaces` and to get details about one, use `get-workspace`.

This could be more consistent.

**Comment by sarasafavi** [comment]
This was resolved in the [1.0.0 release](https://github.com/planetlabs/planet-client-python/releases/tag/1.0.0), to coincide with the migration from API v0 to v1 :+1:
