### ISSUE TITLE
Document a composite by strip workflow in the CLI

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#800]
One little workflow that would be great to document in the CLI would be one that does something like
get the last 5 strips for an AOI, clipped & composited to the AOI.

The API at some point may support 'composite by strip', or we could also use some client-side thing to figure out which results are in the same strip.

**Comment by SFrav** [comment]
I believe composite by strip will be available next month (April 2023). Is there any advanced documentation on this? 
If I understand correctly this will save a lot of wasted downloads.

**Comment by tbarsballe** [comment]
This would have been a nice example, though now that it's been added to the API, less useful.
