### ISSUE TITLE
cannot find CLI auth information, broken link in get-your-planet-account.md

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#811]
**Expected behavior**

Authentication information is found where pointed to in [get-your-planet-account.md ](https://github.com/planetlabs/planet-client-python/blob/main/docs/get-started/get-your-planet-account.md#authenticating-with-the-planet-server)
```
## Authenticating with the Planet server

After you’ve installed the Planet SDK, you can authenticate with the Planet server as outlined in
the [No-Code CLI Guide](../../cli/cli-guide/#authentication)
```
**Actual behavior (describe the problem)**
Clicking that link results in a 404.

**Related Issues**
I'm trying to update CLI auth source docs as a part of #808 / #809

**Comment by JuLeeAtPlanet** [comment]
Content updated. No longer a bug, so "won't fix"
