### ISSUE TITLE
would it be possible to publish a pre-release on conda

### ISSUE THREAD

**Issue by 12rambau** [planetlabs/planet-client-python#812]
I wanted to publish my lib on conda-forge (https://github.com/conda-forge/staged-recipes/pull/21231#issuecomment-1334683374) but the process has been stopped as I'm using version 2 of the planet API. 

the maintainer of conda suggested publishing a pre-release version in the [feedstock](https://github.com/conda-forge/planet-feedstock) following this https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds. 

Is the person managing the feedstocks listening here? If yes would it be possible to do it? 
The version 1 is sending errors/warnings for quite a while and I think a pre-release would be harmless from your side.

**Comment by sgillies** [comment]
@12rambau I have time to look into a conda-forge recipe for a dev version of planet 2. I'll mention you there when I submit a PR.

**Comment by sgillies** [comment]
Continuing at https://github.com/conda-forge/planet-feedstock/issues/31.

**Comment by sgillies** [comment]
Here it is: `conda install -c "conda-forge/label/planet_dev" planet`.

https://anaconda.org/conda-forge/planet.
