### ISSUE TITLE
Allow clipping to MultiPolygon

### ISSUE THREAD

**Issue by ihough** [planetlabs/planet-client-python#826]
**Is your feature request related to a problem? Please describe.**

I would like to clip an order to a `MultiPolygon` area of interest, but `planet.order_client.clip_tool(aoi)` raises if `aoi` is a `MultiPolygon`.

```
aoi = {
    'type': 'MultiPolygon',
        'coordinates': [
            [[[-117.62, 45.22], [-117.61, 45.22], [-117.61, 45.21], [-117.62, 45.21], [-117.62, 45.22]]],
            [[[-117.63, 45.24], [-117.62, 45.24], [-117.62, 45.23], [-117.63, 45.23], [-117.63, 45.24]]]
        ]
}
clip = planet.order_request.clip_tool(aoi)

# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch/lib/python3.10/site-packages/planet/order_request.py", line 336, in clip_tool
#     parameters = {'aoi': geojson.as_polygon(aoi)}
#   File "/opt/homebrew/Caskroom/miniconda/base/envs/torch/lib/python3.10/site-packages/planet/geojson.py", line 54, in as_polygon
#     raise GeoJSONError(
# planet.exceptions.GeoJSONError: Invalid geometry type: MultiPolygon is not Polygon.
```

**Describe the solution you'd like**

`planet.order_client.clip_tool()` should accept a `MultiPolygon` aoi.

**Describe alternatives you've considered**

It works if I manually create the clip tool dict using a MultiPolygon AOI e.g.

```
clip = {'clip': {'aoi': aoi}}
# Works fine to clip an order
```

**Additional context**

**Comment by jreiberkyle** [comment]
Ahh, yes it should accept a MultiPolygon. It will be an easy fix, just change validation to check for Polygon or MultiPolygon.
