### ISSUE TITLE
Crawl the openAPI spec to keep our SDK up to date

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#832]
**Is your feature request related to a problem? Please describe.**
As described in two recent tickets, #780 and #824, the openAPI spec keeps changing and we are playing this game where we try to keep up with the spec, but we have no indication whether or not something has changed, until a bug bubbles up. In the case of #780 and #824, the spec Harmonization tool kept changing, however we only found out by users telling us our SDK was out of date.

**Describe the solution you'd like**
Implement a tool which crawls the openAPI spec which would indicate whether or not our SDK aligns with our API's spec.

I do not know web crawlers well, but here are some potential pre-built tools we could consider:
https://brightdata.com/
https://smartbear.com/
https://www.scrapestorm.com/

**Describe alternatives you've considered**

**Additional context**

**Comment by tbarsballe** [comment]
With the organizational changes to the SDK PSC, there is now closer interaction between the API team and the SDK team

We shouldn't be making API-breaking changes in the first place, and if we are, part of that should be updating the SDK.

As such, this is no longer (as much of a) concern
