### ISSUE TITLE
Remove search-get and search-create

### ISSUE THREAD

**Issue by cholmes** [planetlabs/planet-client-python#839]
We've moved the full saved search functions (#500, #502, #503) to be post-2.0, as they are little used (most people just run a search at once). But we still have 2 of them, search-get and search-create, already implemented. These two together don't do anything useful, as there is no search-run, to actually execute the search you created. So if we don't implement search-run (which hasn't had much interest), we should take the python search-get and search-create functions away from public documentation (can leave them in the core code since we may bring them back later), and also remove the command-line documentation / `--help` files, so people don't see them and get confused.

**Comment by jreiberkyle** [comment]
Now that search-run is implemented, we don't need to remove these commands.
