### ISSUE TITLE
Running a search example 

### ISSUE THREAD

**Issue by Sullumvoe** [planetlabs/planet-client-python#845]
**Expected behavior**
I had expected the code to provide a listing of available IDs for the filter AOIs.

**Actual behavior (describe the problem)**
I received an error message " TypeError: object async_generator can't be used in 'await' expression
**Related Issues**
Please list the ticket numbers (e.g. #708) for any issues already logged in the system.

**Workaround**
Any ways you have found to work around the problem and accomplish your task.

**Minimum, Complete, Viable Code Sample**
A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you.
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
# Your python code here
```
or
```console
> command-line-call
```

**Environment Information**
* Operation System Information (`python -c "import platform; print(platform.platform())"`) linux
* Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)3.10
* Planet package version (`planet -v`)2

**Installation Method**
* conda, pip wheel, from source, etc...conda for most pip for planet
# Search the Data API
async with Session() as sess:
    cl = DataClient(sess)
    *_*items = await cl.run_search(search_id=request['id'])**_
    item_list = [i async for i in items]

async with Session() as sess:
    cl = DataClient(sess)
    items = await cl.run_search(search_id=request['id'])
    item_list = [i async for i in items]
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_48222/944137968.py in <cell line: 1>()
      1 async with Session() as sess:
      2     cl = DataClient(sess)
----> 3     items = await cl.run_search(search_id=request['id'])
      4     item_list = [i async for i in items]

TypeError: object async_generator can't be used in 'await' expression

https://github.com/planetlabs/notebooks/blob/6cc220ff6db246353af4798be219ee1fe7e858b0/jupyter-notebooks/analysis-ready-data/ard_1_intro_and_best_practices.ipynb

**Comment by jreiberkyle** [comment]
This is a bug in the notebook and is logged at https://github.com/planetlabs/notebooks/issues/233. To make it work, just drop the `await`.
