### ISSUE TITLE
Document intersects parameter in CLI

### ISSUE THREAD

**Issue by geowurster** [planetlabs/planet-client-python#85]
It would be nice if the [get scene list](https://www.planet.com/docs/v0/scenes/#get-scene-list) parameters, specifically `intersects`, were exposed in the CLI.  I just had a situation where I wanted to check for scenes intersecting a specific point and had to build an entire GeoJSON file to `$ cat point.geojson | planet search`.  A mild inconvenience, but this would have been much easier:

```
$ planet search --some-flag intersects 'POINT (X Y)'
```

**Comment by ischneider** [comment]
@geowurster This is actually supported (though perhaps not well documented) by just specifying the WKT as an argument:

`planet search 'POINT(-100 40)'`

(I've edited the title to reflect this is a documentation enhancement)

**Comment by geowurster** [comment]
@ischneider Ah great!  Yeah it would be nice to have some usage examples in the main help text.  Can I use a GeoJSON feature or geometry there as well or does it have to be a `FeatureCollection`?

**Comment by ischneider** [comment]
@geowurster indeed some more examples are needed.

When you refer to 'main help text', not sure if this is the CLI help or the README or.. but the more complete documentation is here: https://planetlabs.github.io/planet-client-python/index.html

And specifically: https://planetlabs.github.io/planet-client-python/cli/examples.html

I believe a straight GeoJSON geometry or Feature is supported.

**Comment by geowurster** [comment]
@ischneider By "main help text" I meant the command's [docstring](https://github.com/planetlabs/planet-client-python/blob/master/planet/scripts/__init__.py#L263) that `click` uses as the help text.  Thanks for pointing out the documentation - I didn't see it but that's my fault for not looking at the readme close enough.
