### ISSUE TITLE
Fix broken CLI code examples

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#869]
_Base URL:_ https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-guide/

**General issue:**

- [x]  Most code examples have some prefix from the console (i.e., a "`$`" before the command), which makes copying and pasting the command a nuicence. I highly recommend finding all console prefixes and removing them.

_For example:_ On https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-intro/#collecting-results-with-planet-collect
`$ planet data filter | planet data search PSScene - | planet collect -`

**Data Client:**  https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-data/
- [x] 1. `search` function needs the `--filter` flag.
**Solution:** Add the `--filter` flag before the filter (`filter.json` or STDIN).
_For example:_
`planet data search PSScene filter.json` ➡️ `planet data search PSScene --filter filter.json`
`planet data filter | planet data search PSScene -` ➡️ `planet data filter | planet data search PSScene --filter -`

- [x] 2. `search-quick` function is not supported.
**Solution:** Either change to `search` or remove example.
__For example:_
`planet data filter --range cloud_percent lt 10 | planet data search-quick PSScene -` ➡️ `planet data filter --range cloud_percent lt 10 | planet data search PSScene --filter -`

- [x] 3. `permission` option no longer needs an input.
**Solution:** Remove input to `--permission` flag.
_For example:_ `planet data filter --permission false --asset ortho_analytic_8b_sr | planet data search PSScene -` ➡️ `planet data filter --permission --asset ortho_analytic_8b_sr | planet data search PSScene --filter -` 

**Orders Client:** https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-orders/
- [x] 1. Broken command for `orders list`
**Solution:** `planet** orders --state running` ➡️ `planet orders list --state running`
- [x] 2. STAC output with the composite tool is not currently supported (https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-orders/#clip-composite):
```console
curl -s https://raw.githubusercontent.com/planetlabs/planet-client-python/main/docs/cli/request-json/tools-clip-composite.json \
| planet orders request --item-type PSScene --bundle analytic_sr_udm2 --name 'Streaming Clip & Composite' \
 20220605_124027_64_242b,20220605_124025_34_242b --tools - | planet orders create - 

Error: {"field":null,"general":[{"message":"Unable to accept order: STAC output with the composite tool is not currently supported."}]}
```
- [x] 3. Missing options flags and unneeded ID flag:
`planet orders request PSScene visual --name 'No STAC' --no-stac --id 20220605_124027_64_242b` ➡️  `planet orders request --item-type PSScene --bundle visual --name 'No STAC' --no-stac 20220605_124027_64_242b`

**Extra tips:** https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-tips-tricks/
- [x] 1. Advanced `jq` example returns nothing and needs syntax highlighting
```console
planet orders list | jq -rs '.[] | "(.id) (.created_on) (.state) (.products[0].item_type)"'

(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
(.id) (.created_on) (.state) (.products[0].item_type)
```

**_Note:_** 
- Issues with `planet data filter` piping into `planet data search` are found on:
    - [CLI intro](https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-intro/)
    - [Data API](https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-data/)
    - [Orders API](https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-orders/)
    - [extra tips](https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-tips-tricks/)
- Issues with the `--permission` flag are found on:
    - [Data API](https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-data/)
    - [extra tips](https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-tips-tricks/)

**Comment by JuLeeAtPlanet** [comment]
As noted, Fixed by https://github.com/planetlabs/planet-client-python/pull/892
