### ISSUE TITLE
Update `search-create` CLI and python API commands to match `search`

### ISSUE THREAD

**Issue by jreiberkyle** [planetlabs/planet-client-python#884]
**Expected behavior**
UI of `planet data search-create` and `planet data search` should be similar.

**Actual behavior (describe the problem)**
`planet data search` has filter and name as options, `planet data search-create` has name and filter as arguments.

**Proposed Solution**

Update `search-create` CLI and python API commands to match `search`.

**Comment by cholmes** [comment]
closing this, as the PR merged.
