### ISSUE TITLE
ctrl+c to interupt download of scenes gives you aborted! message but won't give you back control of the console

### ISSUE THREAD

**Issue by danabauer** [planetlabs/planet-client-python#89]
<img width="1280" alt="screen shot 2015-11-20 at 6 23 25 pm" src="https://cloud.githubusercontent.com/assets/751594/11314550/841c7604-8fb4-11e5-8fd8-19c7d3c3faf7.png">

**Comment by sarasafavi** [comment]
Can not reproduce.
