### ISSUE TITLE
Occasional API errors when submitting many searches

### ISSUE THREAD

**Issue by tbarsballe** [planetlabs/planet-client-python#895]
I am using the planet python client in a python script, as a SDK/client for the Data (specifically quick-search) and Order APIs

**Expected behavior**
I expect the client to automatically retry recoverable failures, such that I don't have to build my own retrying logic to work around 4xx rate-limiting responses and similar retryable API responses 

**Actual behavior (describe the problem)**
When submitting a large number of searches (a little over 1000) in a single Session, I have occasionally encountered `planet.exceptions.ServerError` and `planet.exceptions.ServerError.APIError`, resulting in a crash.
Rerunning the search usually works fine.

These failures occur infrequently, and are difficult to reproduce. This is somewhat troublesome, as it is quite likely most developers won't account for them, and run into unexpected failures sometime after writing code against the SDK. **It is quite possible the failures are related to temporary instability or degradation of performance in the Data API, and do not occur under normal circumstances, but I have been unable to confirm one way or another.**

**Related Issues**
#279, #580
In particular, this seems like a reoccurrence of this issue from 580:
> I have also occasionally seen a planet.exceptions.ServerError: Internal Server Error instead, but only when using a shared session among all requests; using a unique session for each request seems to only produce the TooManyRequests error.

The stacktrace from that issue is likely still applicable.
I am using (more or less) the same code as I used when I ran into those issues.

**Workaround**
Wrapping the search code in a try ... catch, adding a two-second delay, and resubmitting appears to work around the issue.
However, given how rarely this actually happens, its hard to tell if this attempt at a workaround actually had any effect.

**Environment Information**
* MacOS 13.2.1
* Python 3.9
* planet-client-python 2.0.0-rc.2

**Installation Method**
* PyCharm integrated package manager

**Comment by jreiberkyle** [comment]
@tbarsballe did this end up being an actual connectivity issue which made the failure legitimate? If so, can we close?

**Comment by tbarsballe** [comment]
I'm still uncertain. I haven't been able to reproduce since, so its probably fine to close this, but I wouldn't be surprised if it eventually crops up again.

My best guess is the API was just under heavy load when I was testing, and experiencing degraded performance.
Those conditions are difficult to replicate, but still not _too_ uncommon.

**Comment by jreiberkyle** [comment]
ok, will close for now and if it crops up again we will figure out what / if we can do about it
