### ISSUE TITLE
Docs - broken link to cli-guide/#cli-set-up

### ISSUE THREAD

**Issue by JuLeeAtPlanet** [planetlabs/planet-client-python#899]
Broken link at https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-guide/#cli-set-up

**Expected behavior**
[Quick Start Guide](../../get-started/quick-start-guide/), so be sure

**Actual behavior (describe the problem)**

points to

../getting-started/quick-start-guide.md

And 404s

**Related Issues**
n/a

**Workaround**
manually navigate

**Minimum, Complete, Viable Code Sample**

Update line 32 of docs/cli/cli-guide.md to:

```
[Quick Start Guide](../../get-started/quick-start-guide/), so be sure
```

**Environment Information**
* website https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-guide/#cli-set-up

**Installation Method**
n/a

**Comment by tbarsballe** [comment]
Can't reproduce; this has evidently been fixed at some point
