### ISSUE TITLE
Link to How to sign on to your Planet account is broken

### ISSUE THREAD

**Issue by JuLeeAtPlanet** [planetlabs/planet-client-python#935]
**Expected behavior**
Go to https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-guide/#cli-set-up
Select the the [Quick Start Guide]

You are linked to: 
https://planet-sdk-for-python-v2.readthedocs.io/en/latest/get-started/quick-start-guide/#step-4-sign-on-to-your-account

**Actual behavior (describe the problem)**

You are linked to (https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/getting-started/quick-start-guide.md) which results in a 404

**Related Issues**
Please list the ticket numbers (e.g. #708) for any issues already logged in the system.

**Workaround**
Any ways you have found to work around the problem and accomplish your task.

**Minimum, Complete, Viable Code Sample**
A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you.
See http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
# Your python code here
```
or
```console
> command-line-call
```

**Environment Information**
* Operation System Information (`python -c "import platform; print(platform.platform())"`)
* Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
* Planet package version (`planet -v`)

**Installation Method**
* conda, pip wheel, from source, etc...

**Comment by tbarsballe** [comment]
This has since been fixed, testing on the current live docs it works fine.
