### ISSUE TITLE
Broken link in Get Started docs

### ISSUE THREAD

**Issue by kevinlacaille** [planetlabs/planet-client-python#980]
This link, https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/getting-started/quick-start-guide.md, at the bottom of this page, https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-guide/, titled "quick start guide link", is broken. I believe it should be pointing to https://planet-sdk-for-python-v2.readthedocs.io/en/latest/get-started/quick-start-guide/.

_TL;DR:_

**Dead link:** https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/getting-started/quick-start-guide.md
**Parent page:** https://planet-sdk-for-python-v2.readthedocs.io/en/latest/cli/cli-guide/
**Link's name:** "quick start guide link"
**Should point to:** https://planet-sdk-for-python-v2.readthedocs.io/en/latest/get-started/quick-start-guide/

**Comment by JSee98** [comment]
@kevinlacaille Here is the PR https://github.com/planetlabs/planet-client-python/pull/999
